src/power_controller.cpp, src/power_controller.hpp
There is a common powerdown for the output amplifier. In case positive
and negative supply are disabled, in order to save more power we disable
the output amplifier.
=> Power Controller: Handle user supply powerdown strobe

src/dmm.cpp
This fixes this build error:
scopy/src/dmm.cpp:41:26: error: ‘make_shared’ is not a member of ‘boost’
ui(new Ui::DMM), signal(boost::make_shared<signal_sample>()),
scopy/src/dmm.cpp:41:26: error: ‘make_shared’ is not a member of ‘boost’
=> src/dmm.cpp: Fix build - add boost/make_shared include

src/dmm.hpp
This fixes:
In file included from scopy/src/dmm.cpp:20:0:
scopy/src/dmm.hpp:69:21: error: field ‘interrupt_data_logging’ has incomplete type ‘std::atomic<bool>’
std::atomic<bool> interrupt_data_logging;
=> scopy: dmm: Fix build error

src/spinbox_a.cpp, src/spinbox_a.hpp
If the input is a measurement value then the text is not case sensitive.
Otherwise the text is case sensitive.
Signed-off-by: Sarca <Septimiu.Sarca@analog.com>
=> Spinbox: Add unit measurement input to spinbox edit control

src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/hardware_trigger.cpp, src/hardware_trigger.hpp, src/osc_capture_params.cpp, src/osc_capture_params.hpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/scope_sink_f.h, src/scope_sink_f_impl.cc, src/scope_sink_f_impl.h, ui/channel_settings.ui
This pull request implements two changes:
1) The adjustable memory depth allows the user to increase the number of acquired samples
for any time base, thus increasing the sampling frequency.
2) Oscilloscope needs to be able to plot samples as soon as they are available. So for large time bases, the user should not wait for the entire buffer. It should wait for the samples that are before the trigger and then display them sequentially.
=> Oscilloscope adjustable memory depth

src/stacked_homepage.cpp, src/stacked_homepage.h, src/tool_launcher.cpp, src/tool_launcher.hpp
The homepage is now updated after using load/reset functionality.
A file can be loaded before the connection to the device is made.  In that case the changes will apply after the connection is done.
The application can be reset either it is connected to a device or not.
=> Fix homepage for load reset scenario

src/la_capture_params.cpp, src/la_capture_params.hpp, src/logic_analyzer.cpp, src/osc_capture_params.cpp, src/osc_capture_params.hpp, src/oscilloscope.cpp, src/pulseview/pv/view/view.cpp
Through this pull request, enhancement #50 is implemented. Both the Oscilloscope and the Logic Analyzer now provide support for delayed acquisitions. No UI element was added to control this. The only element that has control over this feature is the trigger position. 
Once the corresponding buffer size (for the trigger position) moves past the threshold (500000), the delayed acquisition is automatically enabled.
=> Add support for delayed acquisition in OSC and Logic Analyzer

src/tool_launcher_api.hpp
Especially when scripting certain mechanisms, a user may want to make sure
that window doesn't go away when accidentally clicking somewhere else (due
to 'reasons').
This change allows for a `launcher.always_on_top = true` behavior to be
specified, and that will make sure the Scopy window stays on top (in a
pretty insistent manner).
=> ToolLauncher_API: expose the ability to set/unset AlwaysOnTop mode

.gitignore, CI/travis/before_install_darwin.sh, CI/travis/before_install_lib.sh, CI/travis/before_install_linux.sh
The build on master seems to fail currently, because of some fluke/goof with how caching works on Travis CI.
Link: 
https://travis-ci.org/analogdevicesinc/scopy/builds/411606380
Fixed this by patching dependencies only once when they're downloaded.
This also simplifies things on patching in general.
Also fixes the local build of `libad9361-iio` when building Scopy.
=> build: fix Linux build (part 2)

.travis.yml, CI/travis/before_install_linux.sh
Time to also build for Ubuntu 16.04.
Unfortunately, the QT5 libs are still too old for Scopy, so we need to pull
an external Qt5.9 repo from launchpad (similar as for Trusty).
Link is:
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt592-xenial
Same packager also has builds for Xenial.
And we also need to specifically pull the Mesa GL dev libs so that libqwt
builds fine.
=> build,travis-ci: add Xenial builds to the job run

.travis.yml, CI/travis/before_install_linux.sh
Time to also build for Ubuntu 16.04.
Unfortunately, the QT5 libs are still too old for Scopy, so we need to pull
an external Qt5.9 repo from launchpad (similar as for Trusty).
Link is:
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt592-xenial
Same packager also has builds for Xenial.
And we also need to specifically pull the Mesa GL dev libs so that libqwt
builds fine.
=> [for v1.0.1] build,travis-ci: add Xenial builds to the job run

CMakeLists.txt, src/pg_patterns.cpp, src/pulseview/pv/view/viewport.cpp, src/spectrum_analyzer.cpp, src/spinbox_a.cpp, src/tool_launcher.cpp
- Enable the -Wall set of warnings. This increase the awareness of possible coding issues.
- Tell the compiler to treat a couple of these warnings as errors to ensure the warnings don't get overlooked.
Ideally all warnings should be treated as errors or at least a large part of them.  I've added only a a few as there were many unused functions/variables warnings as well as reorder warnings which would require too many code changes for a single PR.
=> Compiler warnings

src/la_channel_manager.cpp, src/pg_channel_manager.cpp
This fixes a issue where channels from the Logic Analyzer or Pattern Generator were able to be dragged and dropped between two instances of Scopy.
=> Logic Analyzer and Pattern Generator small fix

src/main.cpp, src/pattern_generator.cpp, src/pattern_generator.hpp, src/pg_channel_manager.cpp, src/pg_channel_manager.hpp, src/preferences.cpp, src/preferences.h, src/tool_launcher.cpp, src/tool_launcher.hpp, ui/preferences.ui
This PR implements an option to choose whether the Scopy instance loads the digital decoders. The functionality may be limited for the Logic Analyzer and the Pattern Generator if the decoders are not loaded. 
There are 2 ways to disable the decoders:
- Using a command line option: **--nodecoders**
- Using the option listed in the preference panel . (In this case, Scopy needs to be reset manually.  Or should we automatically reset Scopy when the option is checked? This can be discussed here.)
=> Digital instruments: Disable digital decoders support.

src/apiObject.cpp, src/calibration.cpp, src/dbgraph.cpp, src/dbgraph.hpp, src/debug.cpp, src/digitalchannel_manager.cpp, src/digitalchannel_manager.hpp, src/dmm.cpp, src/filter.cpp, src/filter.hpp
These changes fix sign-compare warnings reported by G++ 7.3.
This is not the complete lists. It is a set of changes identified up to this point in time, and more will be identified in the coming days.
=> treewide: fix sign-compare warnings

src/DisplayPlot.cc, src/DisplayPlot.h, src/bitfieldwidget.cpp, src/debugger.cpp, src/external_script_api.cpp, src/graticule.cpp, src/graticule.h
These changes fixes a few unused warnings reported by G++ 7.3.
This is not the complete lists. It is a set of changes identified up to this point in time, and more will be identified in the coming days.
=> treewide: address a few unused warnings

src/plot_utils.cpp, src/plot_utils.hpp
G++ complains in dbgraph.cpp:
```
scopy/src/dbgraph.cpp:200:9: error: deleting object of polymorphic class type ‘adiscope::PrefixFormatter’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
delete formatter;
```
=> src/plot_utils.hpp: define virtual destructor

src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/measure.cpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp
1) This pull request adds a fix for issue #539 . Adding a math channel that results from a division has undefined behaviour (can generate "nan" or infinity/-infinity values ). With this PR, a fix for this scenario is added. 
- On the measurement side, we skip nan values. 
- On the display/plot side, we add a paint filter attribute to handle nan values.
- Output values from math channels are limited to a known value (both positive and negative, which depends on the attenuation for each channel) .
2) On the same flow for the oscilloscope, another fix was added in this PR. Math channels use as inputs the 1st and 2nd channel. If the channels have an attenuation different from 1X, this should be taken into consideration when adding math channels. 
In order to do this, a multiply block is added …
=> Oscilloscope math channel fixes

src/signal_generator.cpp
Related to issue #536
Enable output channels before start of DMA data output. In this way there is no delay between output channels.
Also add check and if channel is disabled from GUI don't release corresponding "powerdown" signal.
Tested on Windows 10 x64.
=> src/signal_generator: powerdown handling change

src/logic_analyzer_api.cpp
If the .ini file had no info about the delay, it would be automatically
initialised to a default value in the Logic Analyzer. This commit makes
sure that it's not set to the default value if something was loaded from
the .ini file.
=> Logic Analyzer: Fix the trigger delay loading process.

CI/travis/before_install_linux.sh
Otherwise there are risks of committing the folder since it shows up
untracked in git.
=> CI/travis/before_install_linux.sh: install breakpad in deps sub-folder

src/adc_sample_conv.cpp, src/info_page.cpp, src/la_capture_params.cpp, src/la_capture_params.hpp, src/la_channel_manager.cpp, src/logic_analyzer.cpp, src/logic_analyzer_api.cpp, src/manual_calibration_api.cpp, src/measure.cpp, src/measure.h, src/menuoption.cpp, src/osc_export_settings.cpp, src/oscilloscope.cpp, src/pattern_generator.cpp, src/pg_channel_manager.cpp, src/pg_patterns.cpp, src/pulseview/pv/view/viewport.cpp, src/scopyApplication.cpp, src/scopyApplication.hpp, src/signal_generator.cpp, src/tool_launcher.cpp
Some bits have been commented out only [vs being removed].
That's because, there is code there that was commented-out instead of being removed.
=> treewide: fix compiler warninges (series 2)

appveyor.yml
Gnuradio will fail to build with boost 1.70. Downgrade boost to 1.69 to match the version with "scopy-mingw-build-deps"
=> Appveyor: downgrade boost to version 1.69

src/debug.cpp
Increase the number of characters being read for an IIO attribute.
Buffer overflows might happen if we use the older value.
=> Debugger: avoid reading corrupt data from IIO attributes

src/pg_patterns.cpp
Loading SPI and I2C patterns was reversed on each load. This fixes it.
=> PatternGenerator: fix loading SPI/I2C pattern data

src/measure.cpp
It seems that p1.m_bufIdx should be checked against p0.m_bufIdx.
This was caught by G++'s parantheses warnings.
=> measure.cpp: fix cross-point check condition

src/DisplayPlot.cc, src/DisplayPlot.h, src/TimeDomainDisplayPlot.cc, src/cancel_dc_offset_block.cpp, src/cancel_dc_offset_block.h, src/dbgraph.cpp, src/dbgraph.hpp, src/filter_dc_offset_block.cpp, src/filter_dc_offset_block.h, src/network_analyzer.cpp, src/network_analyzer.hpp, src/network_analyzer_api.cpp, src/networkanalyzerbufferviewer.cpp, src/networkanalyzerbufferviewer.h, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/preferences.cpp, src/preferences.h, src/startstoprangewidget.cpp, src/startstoprangewidget.h, src/tool_launcher.cpp, src/x_axis_scale_zoomer.cpp, src/x_axis_scale_zoomer.h, ui/network_analyzer.ui, ui/networkanalyzerbufferviewer.ui, ui/preferences.ui, ui/startstoprangewidget.ui
This pull request implements new features for the NetworkAnalyzer:
- Preview the captured buffers and send them into the Oscilloscope: #517
- Add an option for the response channel to remove the DC voltage: #518 
- More options to adjust the phase: #516
- If the response signal is to low, the user will get a warning and know if the Network Analyzer can provide quality readings: #504 
also it fixes some issues:
- less time is spent on a sweep: #194 
- an issue with the phase labeling #515 
- an issue with the plot scale: #509
=> Updated Network Analyzer Tool

src/measure.cpp
Compiler warning is:
````
<scopy>/src/measure.cpp:690:27: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
if (p0.m_name == "MR" && p1.m_name == "LR" ||
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
<scopy>/src/measure.cpp:693:32: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
else if (p0.m_name == "MF" && p1.m_name == "HF" ||
```
=> measure.cpp: add explicit parantheses to logical condition check

src/signal_generator.hpp, src/signal_generator_api.cpp
A consideration was done to use C++ iterators here, but given how the code
is structured using QList + list.at(i) (i.e. matching lists via index in
many places), it looks more consistent to just keep the current indexing
as-is and focus more on the sign-compare warnings directly.
=> signal_generator_api: fix sign-compare warnings with index iterator

src/dmm.cpp
In order to stop other tools that share the m2k adc before starting the dmm.
=> src/dmm.cpp: make sure to first toggle the small run button

src/signal_generator.cpp
Filemanager implementation handles populating the number of samples label
the old way of writing the label needs to be removed.
=> SignalGenerator: fix number of samples on buffered generation

src/oscilloscope.cpp, src/oscilloscope_api.cpp
This bug occurs when saving a configuration with different channels
and channel widget enables. On startup, a different channel will be
selected in Scopy as the one shown in the GUI, causing confusion when
controlling channel specific parameters (such as v/div)
=> Oscilloscope: Fixes bug where wrong channel is selected on startup

src/dbgraph.cpp
Fixes the issues described in: #628 
=> dBgraph: show a minimum of 2 decimals on the y axis scale

src/signal_generator.cpp
This situation can occur when using math function generator
Fixes https://github.com/analogdevicesinc/scopy/issues/640
=> SignalGenerator: Prevent crash when plotting infinite values

src/cancel_dc_offset_block.cpp, src/oscilloscope.cpp, src/oscilloscope.hpp
DC filtering was applied only for the Time plot, while XY and FFT plots had the original signals as input channels. 
This PR adds some changes to redirect the filtered signal to XY and FFT.
=> Oscilloscope: Fix ac coupling for XY and FFT plots

CI/travis/before_install_linux.sh, CI/travis/lib.sh
The version check functions were picked up from:
http://ask.xmodulo.com/compare-two-version-numbers.html
The previous check would only check for Ubuntu Bionic (18.04) and disregard
18.10 & 19.04.
This check should work to include anything starting with 18.04 and newer.
=> build,travis: make ubuntu version check more robust

src/network_analyzer.cpp
=> NetworkAnalyzer: set adc_buffer to nullptr after deleting it

src/spectrum_analyzer.cpp
=> SpectrumAnalyzer: hide averaging value when averaging type is Sample

src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp
The name of the channels will now stay in the range "REF x" where x is from 1 to MAX_REF_CHANNELS
=> SpectrumAnalyzer: refactor reference channel naming

src/signal_generator.cpp
This label better describes the widget's functionality
=> SignalGenerator: change amplitude measurement unit to Volts p-p

src/signal_generator.cpp
=> SignalGenerator: Fix calibration failed when signal generator is active

src/tool_launcher.cpp, src/tool_launcher.hpp
Fixes: "ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x1bdec10. Receiver 'btnCalibrate' (of type 'QPushButton') was created in thread 0x0x149faa0", file kernel/qcoreapplication.cpp, line 563
"
=> ToolLauncher: When the calib thread finishes, then update the UI

src/tool_launcher.cpp
=> ToolLauncher: enable the calibrate button after the calibration

src/pg_patterns.cpp
=> PatternGenerator: prevent floating point errors in clock pattern

src/filemanager.cpp
Check if there is any additional info before exporting.
For spectrum or network analyzers, we have additional information which
gets written to the manager. But the Oscilloscope does not have any,
so we might end up in the case of illegal index access.
=> Oscilloscope: Fix file export

src/tool_launcher.cpp, src/tool_launcher.hpp
Disconnect the thread watcher when a device session is closed.
When the device is connected, the thread watcher is initialized and connected to the worker Q_SLOT, but not disconnected once the device gets disconnected.
This causes issues when connecting and disconnecting multiple times in a single Scopy session, and then using the "Calibrate" button to calibrate.
The calibration process gets called multiple times. Because of sync issues, it's possible that none of the calibration works. Then the device is left in an unknown state.
This should fix issue #712 .
=> ToolLauncher: Fix the calibration button.

src/logic_analyzer.cpp
When Export is pressed the Logic Analyzer is paused, but if nothing is
selected (or Cancel is pressed), it does not resume the capture. This
brings the tool in an unknown state.
=> Logic Analyzer: Fix data export

src/main.cpp
The env. variable for auto scaling breaks things on linux. This fixes the issue.
=> Disable auto screen scaling on Linux

src/dmm.cpp
The data logging mechanism checks the filename member of the DMM to see
where to save the data. Unfortunately this member was not set anymore so
the DMM assumed that no file was given by the user. This commit fixes this
issue
=> dmm: fix data logging

scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
Even though a default path is specified, some systems might override it.
The result is "Scopy" being installed in places where you wouldn't want
it to be installed.
Signed-off-by: Daniel Guramulta <Daniel.Guramulta@analog.com>
=> Windows installer: allow the user to change installation directory

src/network_analyzer.cpp
Setting phase to 0 before generating makes sure that the waveforms
are always generated in phase
=> NetworkAnalyzer: generate reference waveforms in phase

CMakeLists.txt, appveyor.yml
This pull request will install breakpad only on the appveyor build. This will not be built on development machines as the library does not add value for development builds.
=> CMake: Only build breakpad by default on appveyor

CMakeLists.txt, appveyor.yml, scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein, src/frequency_compensation_filter.h, src/frequency_compensation_filter_impl.cc, src/frequency_compensation_filter_impl.h, src/iio_manager.cpp, src/iio_manager.hpp, src/network_analyzer.cpp, src/network_analyzer.hpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_api.cpp, src/oscilloscope_api.hpp, src/preferences.cpp, src/preferences.h, ui/channel_settings.ui, ui/preferences.ui
Filters are only enabled for lowgain mode, as high gain should be calibrated using the trimmers on the M2k. There is an option to show/hide the controls in the oscilloscope channels. The values for the filters are saved in the Scopy.ini file.
=> Add digital filters to the ADC data acquisition flow

src/pg_patterns.cpp
Previously the user had to change the frequency after loading the file
so that the pattern actually loads. This commit fixes it.
=> PatternGenerator: Fix bug with import file

ui/powercontrol.ui
The tracking ratio would only go from 1 to 100, when in fact it should go from 0 to 100
Fixes: #757 
=> powercontrol.ui: set lower limit to 0

src/printableplot.cpp
By default give a file name that has no extension and consider the default selected filter (PDF Document *.pdf). Check the selected filter if the file name is given without an extension and append the extension, otherwise use the extension provided by the user
Should fix: #760 
=> src/printableplot.cpp: fix QFileDialog ignoring selected extension

src/signal_generator.cpp
fixes frequency  approximation bug when switching to trapezoidal waveform
the computed frequency is not displayed correctly causing waveforms to appear
out of sync.
Rounding the frequency using 3 decimals fixes this issue
as 3 decimals are also displayed in the spinbox.
Signed-off-by: Cristina Suteu <cristina.suteu@analog.com>
=> SignalGenerator: fix trapezoidal wave frequency rounding error

src/pg_patterns.cpp, src/pg_patterns.hpp
The pattern generator I2C implementation masks slave NACK responses by pulling the SDA line low at each ACK slot - regardless of whether the pattern gen is reading or writing.
I2C uses an open drain clock (SCL) and data (SDA) line, with each device pulling the SDA line low to communicate. At the end of each byte the sending device should wait for the receiving device to acknowledge the byte with an 'ACK', by pulling the SDA line low for one clock pulse from the master.
There are three possible communication scenarios in I2C that use an ACK that I know of:
1. Following an address byte sent from the master (the slave ACKs)
2. Following a byte written from master to slave (the slave ACKs)
3. Following a byte read from slave to master (the master ACKs)
The pattern gen in scopy is currently …
=> Pattern Generator I2C ACK masking fix

CI/appveyor/build_appveyor_flatpak.sh, CI/appveyor/docker/Dockerfile, CI/appveyor/inside_flatpak_docker.sh
The "latest" Docker image tag is an updated version which has the latest versions for all
the dependencies.
This works now and it will work fine until the next update for some dependency (this time was GNURadio). But I am working on a way to trigger Docker builds (on Dockerhub) every time something happens (it could be a push to the GNURadio repository, Sigrok repository, or it might even be a cron job which builds a new Docker image once a week/month). This way we'll always have an up-to-date Docker image to build our Scopy flatpak on, such that we don't exceed the Appveyor time limit.
=> CI/appveyor/flatpak: Modify the source of the flatpak Docker.

appveyor.yml
MSYS2 introduced a bug  https://github.com/msys2/MSYS2-packages/issues/1960
The current workaround is to update pacman before updating rest of deps
=> appveyor.yml: update pacman before updating rest of deps

appveyor.yml
Issue: https://github.com/msys2/MSYS2-packages/issues/1967
=> appveyor.yml: Fix MSYS2 pacman install. Don't use the latest version.

CI/appveyor/build_appveyor_mingw.sh, CI/appveyor/install_msys_deps.sh
=> ci: use older version of boost as 1.73 currently breaks build

src/signal_generator.cpp
UI modifications:
- update the waveform according to the selected file channel
- file channels do not share the same content anymore
- the size label resets its message if no file is selected.
=> Fix signal generator buffer menu

src/spinbox_a.cpp
Probe attenuation modifies the display scale of Volts/Div and vertical position. When the value exceeded the unit boundaries the display scale should be modified according to the new temporary computed value.
Fixes #814
=> Oscilloscope: Fix vertical display scale.

src/HistogramDisplayPlot.cc
This bug sporadically occurs when a buffer is constant - has the same
value through the buffer. This was tested by creating a synthetic signal
using a gnuradio::analog::sig_source block to feed in a constant waveform.
When this waveform is fed into the flow, the application crashes because
it computes min and max for the signal and eventually computes a difference
which is 0 in this case. In order to prevent this, I provided some default
values for the histogram computation.
=> Oscilloscope: fix crash when receiving a constant signal

src/signal_generator.cpp
This prevents warning/error regarding stairphase being used before init
=> SignalGenerator: initialize stairphase

src/signal_generator.cpp, src/signal_generator.hpp
I messed up the merge in
https://github.com/analogdevicesinc/scopy/commit/14a8521408881e6556ee90eebb86b2b8136f0c62#diff-6142ddf08f6d2cd4b4cfb1b791fd7d20
This commit fixes the get_samples_count for stairstep
=> SignalGenerator: correctly set samples count for stairstep

ui/trigger_settings.ui
from general trigger settings to internal only settings
By doing so, when the internal trigger is grayed out, the channel is
grayed out as well. This is due to only using TI as trigger-in pin and
TO as trigger-out pin. This is implemented in libm2k but was not correctly
showed in the UI.
Moved channel from below <auto/manual> to the location in the screenshot.
Disabling internal trigger will disable channel selection
=> OscTriggerSettings: Move trigger channel selection widget

src/FftDisplayPlot.cc, src/FftDisplayPlot.h, src/average.cpp, src/average.h, src/fft_block.cpp, src/fft_block.hpp, src/network_analyzer.cpp, src/network_analyzer.hpp, src/network_analyzer_api.cpp, src/network_analyzer_api.hpp, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, src/spectrum_analyzer_api.cpp, src/spectrum_analyzer_api.hpp, src/spinbox_a.cpp, src/stream_to_vector_overlap.h, src/stream_to_vector_overlap_impl.cc, src/stream_to_vector_overlap_impl.h, ui/network_analyzer.ui, ui/spectrum_analyzer.ui
Network Analyzer:
-  Add averaging.
-  Add a control for the min number of periods per capture.
-  Increase the number of captured samples.
Spectrum Analyzer:
-  Increase the max number of averages and display the current average buffer.
-  Add a Gain control for each channel.
-  Increase the possible bin size.
-  Add a new unit (Volts per square root hertz) for noise spectral density.
=> Spectrum and Network analyzer: fixes and enhancements

src/oscilloscope_plot.cpp
=> Oscilloscope: change unit from Hz to sps for sample rate in osc plot

CMakeLists.txt, src/network_analyzer.cpp
Because of ambigous reference to gr::analog or libm2k::analog. Fixes
compilation error
=> NetworkAnalyzer: use full namespace for analog

CI/appveyor/before_install_lib.sh, CI/appveyor/install_ubuntu_deps.sh, CMakeLists.txt
This PR handles 2 issues that were found on MacOS.
1) The Qwt official repo removed the MathML module, so we need to update the Scopy Qwt Patch to drop the module as well.
2) The decoders were not copied in the MacOS bundle file, so the App would always start with a pop-up informing the user that the digital decoders will not work.
=> MacOS Appveyor fixes

CI/appveyor/install_macos_deps.sh
We locked the builds to Qt 5.14.2 because Qt introduced a bug in Qt 5.15.0,
related to QPushButtons. Installing an older Brew formula using the github
Formula file was deprecated in the last couple of days and stopped working
for our build. Building the desired 5.14.2 version from source would take
too much time and would fail on our Appveyor builds.
Fortunately, Brew added today the 5.15.1 Formula on the official
repositories, so we can now use this updated version (this version
introduces the QPushButton fix that we needed.)
=> Appveyor MacOS: Update Qt to 5.15.1 for MacOS builds.

src/iio_manager.cpp, src/iio_manager.hpp, src/logic_analyzer_sink_impl.cpp, src/logicanalyzer/logic_analyzer.cpp, src/mixed_signal_sink.h, src/mixed_signal_sink_impl.cpp, src/mixed_signal_sink_impl.h, src/oscilloscope.cpp, src/oscilloscope.hpp
- Fix the mixed acquisition (there should no longer be any desync)
- Add a mixed signal sink
- The iio_manager will be configured with the mixed sink when started from the oscilloscope with mixed signal enabled
- Stacked decoders are now available in the mixed signal view
- Crashes that occured in the mixed signal view were fixed, the tool should now be more stable
=> Fixes and improvements regarding the mixed signal view

src/spectrum_analyzer.cpp
If the Spectrum is running, ui->runSingleWidget->toggle(false); will call sample_timer->stop which is deleted at that time.
=> SpectrumAnalyzer: fix crash

src/logicanalyzer/logic_analyzer.cpp, src/oscilloscope.cpp, src/oscilloscope_plot.cpp, src/patterngenerator/pattern_generator.cpp, src/trigger_settings.cpp, src/trigger_settings.hpp, ui/trigger_settings.ui
1. fixes regarding crashes when disabling the mixed signal view
2. when a new group is created select the first channel in it
3. fix the position on decoders in the mixed signal view menu
4. add information about how mixed signal view affects scopy when enabled
5. disable some trigger settings that won't work with the mixed signal view
6. make sure the stacked decoder button is correctly shown and set
=> Logic fixes

src/calibration.cpp, src/iio_manager.cpp, src/iio_manager.hpp, src/power_controller.cpp, src/spectrum_analyzer.cpp, src/tool_launcher.cpp, src/tool_launcher.hpp, src/toolmenuitem.cpp, src/toolmenuitem.h
- Unplugging the board during the calibration should not crash the app, even if the calibration is throwing exceptions. We handle those and disconnect without errors.
- Unplugging the board during the tool construction should not crash the app, even if the constructors are throwing exceptions. We handle those in the Tool Launcher and disconnect without errors.
- We should not suppose that the calibration and connection were done well and all the tools are available from that point on.
- Make sure the Power Supplies are not ON when first connecting to a board.
- Don't use averaging in the "Sample" Type for Spectrum Analyzer.
=> Fix issues related to exception handling while unplugging the board.

src/DisplayPlot.cc, src/DisplayPlot.h, src/logicanalyzer/logic_analyzer.cpp, src/oscilloscope_plot.cpp, src/patterngenerator/pattern_generator.cpp, src/patterngenerator/patterns/patterns.cpp, src/patterngenerator/patterns/patterns.hpp
- Fix for: #884 
- Logic channels where not initially positioned in the right place.
- The scroll in the LA/PG was only moving "DIO0"
=> General Fixes

src/tool_launcher.cpp
Undefined behavior bug: after a certain number of disconnections, the instruments will not be initialized properly.
=> ToolLauncher: Fix crash.

src/preferences.cpp
I missed this initialization when implementing https://github.com/analogdevicesinc/scopy/pull/833
=> Preferences: initialize sig_gen_nr_of_periods to 1

CI/appveyor/extract_msys_deps.sh, CI/appveyor/install_msys_deps.sh, appveyor.yml
Use the old deps archive provided by scopy-mingw-build-deps instead of trying to get packages from repo.msys2.org.
Some older packages might be removed from the official repo. Using this
change, we don't depend on that official repo to build our application.
Also, remove the fast_finish flag, we want to use the MacOS builds whether
the Mingw build fails or not.
=> appveyor: Use the old deps archive provided by scopy-mingw-build-deps

CI/appveyor/build_appveyor_mingw.sh, scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
The checkbox for a task is checked by default, so we don't need to specify
another flag.
Also, the Appveyor job no longer needs to export an empty Scopy.ini.
=> WindowsInstaller: Use "Tasks" to create checkbox that deletes Scopy.ini.

CI/appveyor/build_appveyor_mingw.sh
Appveyor build failed because the RC compiler detection failed.
This might be caused by the CMake package update (checked repo.msys2.org and the update was done 2 days ago, when the builds started failing).
CMake does not detect an appropriate compiler for RC, so we point it to the right path.
=> Appveyor: Use mingw64/bin/windres as RC compiler for 64 bit.

src/preferences.cpp
This will ensure that the preferences have been initialized correctly.
This fixes a bug when changing from the first language in the combobox,
not requesting a restart because Preferences menu doesn't detect correct
initialization
=> Preferences: assume preferences menu initialized when shown

CI/appveyor/package_darwin.sh
Appveyor macos: We are now using python 3.9 which is the latest provided by 
brew, appveyor and required by the latest Glib (which is required by
libsigrokdecode).
We want to fix the Python version to 3.8, until we figure out how to do it,
we will use Python 3.9 for MacOS installers.
=> Appveyor macos: We are now using python 3.9 which is the latest.

src/oscilloscope_plot.cpp
Should fix the second reported bug in this issue: https://github.com/analogdevicesinc/scopy/issues/894
=> CapturePlot: when loading groups ignore the current selected channel

src/oscilloscope.cpp
This happens because a label with no parent is set visible before
inserting it in a layout
=> Oscilloscope: prevent popup when creating instrument

src/saverestoretoolsettings.h
This macro was only introduced in QT 5.13. Manually write the delete copy constructor/assignment and move constructor/assignment so we don't force the usage of Qt 5.13
=> SaveRestoreToolSettings: drop usage of Q_DISABLE_COPY_MOVE macro

src/debug.cpp, src/debugger.cpp, src/manualcalibration.cpp
Manual Calibration: 
- Fix the file dialog used for calibration saving.
- Make sure the tool does not use the calibration coefficients in the calibration process (since this will alter and output wrong calib coefficients).
Debugger:
- Fix the way attributes are loaded (whether they have available values or not).
The calibration coefficients will properly work in Scopy only after the corresponding libm2k PR is merged ( https://github.com/analogdevicesinc/libm2k/pull/207 ) and the scopy-mingw-build-deps is rebuilt to contain the new version.
=> Manual Calibration and Debugger fixes

src/patterngenerator/patterns/patterns.cpp
This overflow occurs when the requested buffersize is smaller than the
requested/suggested buffersize by the pattern
=> PatternGenerator: Fix overflow in SPI and UART pattern generation

src/logicanalyzer/logic_analyzer.cpp, src/logicanalyzer/logic_analyzer.h, src/logicanalyzer/logicanalyzer_api.h, src/logicanalyzer/logicdatacurve.cpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/patterngenerator/pattern_generator.cpp, src/plot_line_handle.cpp, src/scopyExceptionHandler.h, src/trigger_settings.cpp, src/trigger_settings.hpp, ui/logic_analyzer.ui, ui/oscilloscope.ui, ui/trigger_settings.ui
This pull request implements enhancements for the Logic tools as described in the following issues:
- #961 
- #958 
- #949 (w/o the plotting artefact)
=> Enhancements

src/power_controller.cpp
The PowerSupply suffered from the same issue that was affecting the Voltmeter: 1e34d17dd68706ce3c50503cef72b438dcf4a91b
=> PowerSupply: fix GUI after editing .ui file

src/debugger.cpp, src/qtgui_util.cc, src/utils.h
From the docs: The comparison predicate must define a strict weak ordering.
This fixes an issue/crash that only appeared on MacOS due to libc++
in LLVM - which compares an element with itself.
We now use a function to compare strings naturally.
=> debugger.cpp: Change the comparison for channel sorting using std::sort.

ui/preferences.ui
Preference options start to add up and no longer have space in the default menu. Adding a scroll area fixes the issue
=> Preferences: UI: morph the main widget into a scroll area

src/info_page.cpp, src/phonehome.cpp, src/phonehome.h
The phonehome firmware label was updated before actually getting firmware
information from the board, causing it to always return firmware update
required
=> phonehome: fix phonehome firmware label

src/logicanalyzer/logic_analyzer.cpp
Make sure to delete the plot curves after closing the capture thread, otherwise while the thread is being stopped it might emit that new data is available to some curves that are deleted, resulting in a segfault
=> LogicAnalyzer: fix bug when closing scopy while logic is running

CI/appveyor/build_appveyor_macos.sh, CI/appveyor/install_macos_deps.sh, CI/appveyor/package_darwin.sh, appveyor.yml
Install qt5 and make sure that the correct path to it is found and used for tools like qmake and macdeployqt
=> Appveyor: fix MacOS job

src/patterngenerator/patterns/patterns.cpp
This change will avoid creation of tiny buffers.
Number Pattern uses this function.
Signed-off-by: Teo Perisanu <Teo.Perisanu@analog.com>
=> PatternGenerator: Set min sampling frequency to 1kHz.

ci/azure/lib.sh
Since the feature was implemented, pip install cmakelang will no longer add the tools(including cmake-format) to PATH, so we need to call the executable with the full path
=> ci: azure: fix cmake-format not in PATH

src/patterngenerator/pattern_generator.cpp
The output mode button will now properly be set to correspond to the output mode of the channel
=> PatternGenerator: display correct output mode for each channel

src/logicanalyzer/logic_analyzer.cpp
=> LogicAnalyzer: ExternalTrigger: do not enable options when source is osc

scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
If the drivers are already installed, show the box but make it unchecked.
=> Windows installer: Rework the drivers install checkbox.

scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
A checkbox is added in the uninstaller wizard, unchecked by default, which allows the user to remove the ADALM2000 drivers when Scopy is removed.
=> scopy.iss: Custom Scopy uninstaller for removing the ADALM2000 drivers.

scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
Check if there is another Scopy version installed at the same chosen
location and allow to user to choose whether to uninstall and then install or
just overwrite everything (leftover files might appear in this case).
know limitation: HKLM value for previous app version only returns the last installed
version.
=> windows installer: Rework the overwriting method used in the Win installer.

CI/appveyor/install_macos_deps.sh, CI/appveyor/install_ubuntu_18_deps.sh, CI/appveyor/install_ubuntu_20_deps.sh
=> MacOS and Linux builds: Lock libiio version to v0.21 for now.

CI/appveyor/build_appveyor_macos.sh
=> build_appveyor_macos.sh: Set the min accepted macos version to 10.13.

resources/scopy.html
A lot of questions get posted in the wrong section of EZ (this link might
be one reason why?)
=> scopy.html: Fix Engineer Zone link on the Scopy homepage.

android/src/org/adi/scopy/ScopyApplication.java
Previously the application crashes if there is no gnuradio folder in
external storage root. This fixes it by setting an envvar to the cache
of the application.
=> android: fix gnuradio in external storage bug

CMakeLists.txt
=> cmake: use cxx compiler instead of c for stylesheets preprocessing

resources/stylesheets/templates/default.qss.c, resources/stylesheets/templates/light.qss.c, src/gui/tool_view.cpp, src/logicanalyzer/logic_analyzer.cpp, src/network_analyzer.cpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp, src/patterngenerator/pattern_generator.cpp, src/preferences.cpp, src/preferences.h, src/qtgui_util.cc, src/signal_generator.cpp, src/spectrum_analyzer.cpp, src/tool.cpp, src/utils.h, ui/logic_analyzer.ui, ui/measure_panel.ui, ui/network_analyzer.ui, ui/oscilloscope.ui, ui/pattern_generator.ui, ui/preferences.ui, ui/spectrum_analyzer.ui
- re-added the fixed plots 
- added preferences option for dockable/undockable widgets
- re-arranged QDockWidgets 
- styled QDockWidgets
- removed margins surrounding plots
- disabled floating widgets on android
- fixed size of general setting menu in logic analyzer
- cherry-picked from #1190 : hide buffer previewer for logic analyzer, re-added min sized for capture plot, fix bad UI rendering
=> Docking mechanism fixes

src/FftDisplayPlot.cc
Calling repaint tries to force an immediate repaint and causes hangs on MacOS - in software rendering mode).
=> FftDisplayPlot.cc: Use update instead of repaint 

CI/appveyor/inside_flatpak_docker.sh
Otherwise we don't build the current commit for Scopy, we just build
what's hardcoded in the json.c file.
=> inside_flatpak_docker.sh: Run the preprocess step to generate the json file, then disable the auto preprocessing at build time.

src/tool_launcher.cpp
macOS bundle already comes with high-resolution `.icns` file. Calling unconditionally `QApplication::setWindowIcon(QIcon(":/icon.ico"))` causes macOS replace high quality icon with low resolution one.
Alternatively we might want to limit `setWindowIcon` to Windows platform.
=> macOS: Do not replace app icon with low-resolution .ico on startup

src/preferences.cpp, src/preferences.h
Preference checkboxes get visually updated only on showEvent, but they trigger other changes in the preference mechanism (example: OpenGL default on Android/MacOS/Windows - setup env var which is used in the app later on). They should be initialized in the constructor, right after creating the preference menu. We shouldn't rely on showEvent and wait until the Preference menu is opened.
=> preferences: Fix preferences initialization at startup, don't rely on showEvent() to initialize them.

.github/workflows/androidbuild.yml
Building the APK and deps in release mode implies signing the package.
For now we can use debug mode, in order to test the release candidate.
https://github.com/analogdevicesinc/scopy-android-deps/commit/b16d52d1b7b2d7f5a76a41d282fe576c0a47f456
=> Temporary: Use another docker image for the Android builds, with debug libs.

src/oscilloscope.cpp
This is v/div is used to compute the gain of the m2k. If it is not updated
immediately, the gain setting lags behind. Alternatively a different way
of computing the gain setting could be implemented.
=> oscilloscope: update plot axis after setting v/div

CI/appveyor/inside_mingw_docker.sh
The ISS file is needed when creating the release installer.
=> CI/inside_mingw_docker.sh: Export .iss file to scopy archive artifact.

src/oscilloscope.cpp
This ensures that the xy plot is correctly initialized
=> oscilloscope: move setup_xy_channels after main plot is initialized

resources/stylesheets/templates/default.qss.c, resources/stylesheets/templates/light.qss.c
these were visible on Windows, in osc -> mixed signal menu and the tabs of the dock widgets
=> gui: removed frames for QScrollArea and QTabBar

src/oscilloscope.cpp
Hardware is clamped to +/-25V by the spinbox
=> oscilloscope: do not set offset limits for plotting

src/handlesareaextension.cpp
instead of computing the value on his own.
=> plots: yleft axis ruler will take values from qwtscaleengine

ui/logic_analyzer.ui, ui/network_analyzer.ui, ui/oscilloscope.ui, ui/pattern_generator.ui
All tools have the buttons aligned to the right with 15px spacing
=> general: fix spacing of top right buttons

CMakeLists.txt
Small misunderstanding caused changing the path here in the first place
=> cmake: fix icon location for scopy application on linux

resources/stylesheets/templates/default.qss.c, resources/stylesheets/templates/light.qss.c
Since Qt does not support HiDPI SVG assets on border-image and background-image having different size images on the same position will cause the image to look bad the solution is to replace "border-image" or "backgroud-image" with "image" or "icon" and set "border: none;"
=> general : dmm menu arrows style fix

src/tool_launcher.cpp, src/toolmenu.cpp
=> Fix generic device issues

resources/filter.json
For now, DMM, OSC, Spectrum and Signal Gen all work using gr-m2k.
In the future we'll enable back all these tools.
=> pluto-devices: Clean up the device compatibility list for ADALM-Pluto.

src/gui/measure.cpp, src/logicanalyzer/logic_analyzer.cpp, src/network_analyzer.cpp, src/oscilloscope.cpp
Calling set_kernel_buffers_count() right after destroying a buffer might
return EBUSY because the file descriptor is still in use.
Also, kernel buffers count should not be changed while acquisition is
in progress.
=> Implement a busy retry when setting kernel buffers.

src/filemanager.cpp, src/filemanager.h, src/gui/dropdown_switch_list.cpp, src/logicanalyzer/annotationcurve.cpp, src/logicanalyzer/annotationcurve.h, src/logicanalyzer/annotationdecoder.cpp, src/logicanalyzer/decoder_table.cpp, src/logicanalyzer/decoder_table.hpp, src/logicanalyzer/decoder_table_item.cpp, src/logicanalyzer/decoder_table_item.hpp, src/logicanalyzer/decoder_table_model.cpp, src/logicanalyzer/decoder_table_model.hpp, src/logicanalyzer/genericlogicplotcurve.cpp, src/logicanalyzer/genericlogicplotcurve.h, src/logicanalyzer/logic_analyzer.cpp, src/logicanalyzer/logic_analyzer.h, src/logicanalyzer/rowdata.cpp, src/logicanalyzer/rowdata.h, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/preferences.cpp, src/preferences.h, src/tool.hpp, ui/logic_analyzer.ui, ui/preferences.ui
Groups decoders by messages
- cannot run LA when table is open, only single button is available
- information about decoder messages (sample, duration) can be enabled in preferences
- clicking rows in table will zoom in the plot on the message
- clicking annotations in plot will select the equivalent row in table (if available)
settings:
- selectable decoder
- selectable primary annotation type (groups annotations by the specified type)
- filter unwanted annotations
- regex search (only searches through what is visible with the current settings)
work in progress...
https://user-images.githubusercontent.com/92979643/188131356-e7c6426e-4121-40af-b8aa-800db21ee86e.mp4
=> Implemented decoder table for logic analyzer

src/logicanalyzer/binding/decoder.cpp
logic analyzer: fixed bug causing to stop decoding when changing decoder settings
- bug only happened on windows
=> Windows decoder bug fix

plugins/debugger/src/debuggerplugin.cpp
If the Instrument is detached, this causes illegal memory access when disconnecting from the device.
=> DebuggerPlugin: Use deleteLater for the instrument on disconnect.

plugins/m2k/src/m2kcontroller.cpp
Scopy sometimes crashes in the CyclicTask destructor when trying to stop an assigned task and the task is being destroyed.
=> M2kController: Fix the deletion order of the ping task and timer.

core/include/core/application_restarter.h, core/src/application_restarter.cpp, pluginbase/include/pluginbase/preferences.h, pluginbase/src/preferences.cpp
- preferences are now saved on aboutToQuit signal instead of inside the destructor
- made ApplicationRestarter a singleton
=> Loading preferences on restart bug fix

core/src/scopymainwindow.cpp
This will work on the official installer. In local builds(development) we will need to implement a CMakeLists setup of SCOPY_PYTHONPATH when SCOPY_DEV is true. But for now, we need the Windows official installer to work.
Tested this on Windows and compared it with the current dev branch installer. Scopy will start on this version, I was able to connect to M2K and start the Logic Analyzer decoders with correct data displayed on the screen. In the meantime, the Scopy version installed from the current dev branch will not start.
@bindea-cristian will take a look at adding the SCOPY_PYTHONPATH env var when in SCOPY_DEV mode.
=> ScopyMainWindow.cpp: Load Python on WIN before trying to load decoders.

windows/scopy-32.iss.cmakein, windows/scopy-64.iss.cmakein, windows/scopy.iss.cmakein
Starting with InnoSetup version 6, the default value for MinVersion is 6.2.sp1 which might break installation on newer Windows versions.
=> scopy.iss.cmakein: Set a specific value for MinVersion to avoid the default.

gui/ui/channel.ui
This causes the channel to initialize as checked when Scopy is started for the first time. From the second run onward the API object will save the enabled value (since it is marked as Q_PROPERTY) and override the default "checked" value with the value from the last run.
=> ChannelWidget: added default enabled value

core/src/devicebrowser.cpp
Set fixed height in order to avoid unnecessary resizes
=> DeviceBrowser: set fixed height

gui/include/gui/buffer_previewer.hpp, gui/src/buffer_previewer.cpp
- the previewer curve is only generated if the widget was vertically resized
=> Buffer previewer optimization

plugins/m2k/src/old/oscilloscope.cpp, plugins/m2k/src/old/oscilloscope.hpp
rail_ff causes the value to lose precision based on the max/min values
=> oscilloscope: fix math bug that loses precision of the signal

src/patterngenerator/patterns/patterns.cpp
- Fix the generation of the clock sequence to ensure clock edges at fixed locations.
- Align the data sequence to the clock edges, previously was the other way around and edge cases due to CPHA were not handled correctly.
- NOTE: when CPHA=1 data sequence is shifted with T_ck/2 at the start. When CPHA=0 an aditional T_ck/2 is added at the end of the sequence. This preserves the data sequence length and ensures normal behaviour when changin the bytes per frame.
- LINK: https://upload.wikimedia.org/wikipedia/commons/f/f0/SPI_timing_diagram_CS.svg
=> patterngenerator/spi: fix SPI generation

src/gui/hoverwidget.cpp
qDebug(CAT_HOVERWIDGET) was causing scopy fail build
=> Eliminated logging category from debug message

gui/include/gui/animationpushbutton.h, gui/src/animationpushbutton.cpp
If the stopAnimation method is not called in a specified time interval by the client (10 seconds by default), the method will be triggered automatically once the timer reaches its timeout.
=> Added a timer for AnimationPushButton.

src/preferences.cpp
- settings with required restart kept asking for it even after restarting the app
=> Scopy 1.5: fixed preferences asking for restart

iioutil/include/iioutil/connectionprovider.h, iioutil/src/connectionprovider.cpp, iioutil/test/tst_connectionprovider.cpp
Allow open/close on Connection objects using either URI, iio_context or existing Connection object. This would reduce the code complexity when URI is not available in certain code structures.
=> iioutil/connectionprovider: add open/close Connection using iio_context.

.github/workflows/mingwbuild.yml, ci/windows/build_and_create_installer.sh
3 artifacts are now published for every Windows CI build:
- scopy-windows-x86_64 -> archive with stripped binaries
- debug-windows-x86_64 -> archive with unstripped binaries (the original one with full size binaries)
- scopy installer ( based on the stripped binaries)
The archive size was reduced to ~350mb from ~900mb.
The installer size was reduced to ~50mb from ~150mb.
=> ci/windows/build_and_create_installer:strip debug symbols to reduce size.

src/tool_launcher.cpp
Fix the following scenario in Scopy using libm2kv0.8.0: connect, disconnect, connect again - fails due to improper libm2k context deletion. See PR #1553 for more details on this issue.
=> Scopy 1.5.0: tool_launcher: close all libm2k contexts when disconnecting the M2K.

gui/include/gui/widgets/scopystatusbar.h, gui/src/widgets/scopystatusbar.cpp
The clearStatusMessage method was called after the ScopyStatusBar widget had been destroyed.
=> ScopyStatusBar fix.

gr-util/src/grdeviceaddon.cpp, gr-util/src/grproxyblock.cpp, gr-util/src/grsignalpath.cpp, gr-util/src/grsignalsrc.cpp, gr-util/src/grtimechanneladdon.cpp, gr-util/src/grtimeplotaddon.cpp, gr-util/src/grtimeplotaddonsettings.cpp, gr-util/src/grtopblock.cpp, gr-util/src/measure.cpp, gr-util/src/measurementcontroller.cpp, gr-util/src/timechanneladdon.cpp, gui/src/basictracker.cpp, gui/src/cursorcontroller.cpp, gui/src/plotmagnifier.cpp, gui/src/plotnavigator.cpp, gui/src/plottracker.cpp, gui/src/plotzoomer.cpp, iio-widgets/src/datastrategy/cmdqchannelattrdatastrategy.cpp, iio-widgets/src/datastrategy/cmdqdeviceattrdatastrategy.cpp, tools/format.sh, tools/includemocs.sh
=> tools: format.sh skip build folder

core/include/core/scopymainwindow_api.h, core/src/cmdlinehandler.cpp, core/src/scopymainwindow_api.cpp, main.cpp, tools/js/README.md
The method no longer requires the contents of the script as a parameter and does not automatically close the application.
Closing the application can now be managed by the user both from the command line through the --keep-running (r) option and from ScopyJS through runScript(QString scriptPath, bool exitApp) method.
=> core/scopymainwindow_api: Changed runScript method.

gui/src/plotwidget.cpp
Until now, only the y-axis was hidden...
=> gui/plotwidget: Hide x axis labels.

tools/plugingenerator/plugin_generator.py
When a new plugin is generated the path to the export file is added to the .gitignore.
=> tools/plugingenerator: Add plugin export file to .gitignore.

gui/include/gui/widgets/plotbufferpreviewer.h, gui/src/buffer_previewer.cpp, gui/src/widgets/plotbufferpreviewer.cpp, plugins/datamonitor/src/datamonitor/monitorplot.cpp
data limit now has min and max value instead of beeing the absolte diff between two values
use lower and upper axis bound instead of axis min and max value on drag to account for zoom level
=> bufferpreviewer: fixed rolling mode bug

plugins/regmap/src/regmapplugin.cpp, plugins/regmap/src/xmlfilemanager.cpp, plugins/regmap/xmls/ad74413r.xml, plugins/regmap/xmls/regmap-config.json
Fixed 2 bugs on regmap 
* Map was only creating for AXI devices
* offset value and bit offset values were treated as hexa values
=> Bug regmap offset values

plugins/iiodebugplugin/src/iiostandarditem.cpp
There might be cases when the return code from iio_device_get_trigger is 0 (success) but the trigger is nullptr. Add check for such events.
=> Fix IIODebugger nullptr trigger

plugins/datalogger/CMakeLists.txt, plugins/swiot/CMakeLists.txt
I added the sub-directories from datalogger/include/dataloggerplugin and swiot/include/swiot as target_include_directories in the cmakelists specific to each plugin.
=> Plugins CMakeLists: Include sub-directories

plugins/datalogger/src/dataloggerplugin.cpp, plugins/iiodebug/src/iiodebugplugin.cpp, tools/plugingenerator/templates/plugin_src_template.mako
The template does not actually create a plugin page, so it should return false
=> tools/plugingenerator.py: return false to load page

plugins/datalogger/src/datamonitor/sevensegmentdisplay.cpp, plugins/datalogger/src/dmm.cpp, plugins/datalogger/src/menus/channelattributesmenu.cpp, plugins/datalogger/src/menus/datamonitorsettings.cpp, plugins/datalogger/src/menus/monitorselectionmenu.cpp, plugins/datalogger/src/menus/plottimeaxiscontroller.cpp, plugins/datalogger/src/menus/sevensegmentmonitorsettings.cpp
Changes made to remove warnings 
on windows system spinbox min and max values don't work if using "(double)((long)(-1 << 31))" for value
=> datalogger: fixed warning messages

gui/include/gui/stylehelper.h, gui/include/gui/widgets/titlespinbox.h, gui/src/stylehelper.cpp, gui/src/widgets/titlespinbox.cpp, iio-widgets/include/iio-widgets/guistrategy/comboguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/editableguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/rangeguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/switchguistrategy.h, iio-widgets/include/iio-widgets/iiowidgetbuilder.h, iio-widgets/src/guistrategy/comboguistrategy.cpp, iio-widgets/src/guistrategy/editableguistrategy.cpp, iio-widgets/src/guistrategy/rangeguistrategy.cpp, iio-widgets/src/guistrategy/switchguistrategy.cpp, iio-widgets/src/iiowidgetbuilder.cpp
Compact mode reduces the size of the IIOWidgets to a single line. It can be toggled on/off by the compactMode() function in the builder.
=> iio-widgets/UIStrategy: Add compact mode to UI Strategies

gr-util/CMakeLists.txt
gr-gui is included in the m2k module. For this reason when we disable the m2k plugin the build fails.
=> gr-util: gr-gui library is never used.

plugins/m2k/src/m2kplugin.cpp, plugins/swiot/src/swiotplugin.cpp
The cyclical task should be deleted first because it depends on the ping task.
=> Fix ping bug

plugins/swiot/res/emu_xml/config.xml, plugins/swiot/res/emu_xml/config2.xml, plugins/swiot/res/emu_xml/runtime1.xml, plugins/swiot/res/emu_xml/runtime2.xml
The old name causes the device to be disconnected by ping.
=> swiot/emu_xml: Changed trigger device name to sw_trig.

core/src/scopymainwindow.cpp, core/src/scopypreferencespage.cpp, iio-widgets/include/iio-widgets/iiowidget.h, iio-widgets/src/iiowidget.cpp, iio-widgets/src/iiowidgetbuilder.cpp, pluginbase/include/pluginbase/lazyloadwidget.h
The IIOWidget now has the ability to lazy load. By default (if not changed from the preference page) the IIOWidgets will only initialise on the first show event, not in the constructor, thus improving the loading time when connecting to a device. Deselecting this option will make the IIOWidgets initialise when created.
=> IIOWidget: Add optional lazy loading

.gitignore, doc/local-windows-build-readme.md
**`CMakeLists.txt`**
Added post-build in CMake to copy .DLL files in build directory for launching and debugging Scopy in Windows
**`cmakelists_template.mako`**
Adjusted CMakeLists template for plugins to output generated libraries in plugins directory
**`local-windows-build-readme.md`**
Documented build process for local Windows environment
=> Windows build documentation

src/network_analyzer.cpp
- The crash occurred because the iteration thread computing the average was updating a UI label with the average value for each iteration too frequently.
=> network_analyzer: fix UI crash when averaging is performed

pluginbase/src/preferences.cpp
Initialized s with nullptr. The fact that it was not initialized caused unwanted behaviors.
=> Bug fix: preferences

iio-widgets/include/iio-widgets/datastrategy/channelattrdatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/cmdqchannelattrdatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/cmdqdeviceattrdatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/contextattrdatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/deviceattrdatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/multidatastrategy.h, iio-widgets/include/iio-widgets/datastrategy/triggerdatastrategy.h, iio-widgets/include/iio-widgets/guistrategy/comboguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/editableguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/rangeguistrategy.h, iio-widgets/include/iio-widgets/guistrategy/switchguistrategy.h, iio-widgets/src/datastrategy/channelattrdatastrategy.cpp, iio-widgets/src/datastrategy/cmdqchannelattrdatastrategy.cpp, iio-widgets/src/datastrategy/cmdqdeviceattrdatastrategy.cpp, iio-widgets/src/datastrategy/contextattrdatastrategy.cpp, iio-widgets/src/datastrategy/deviceattrdatastrategy.cpp, iio-widgets/src/datastrategy/multidatastrategy.cpp, iio-widgets/src/datastrategy/triggerdatastrategy.cpp, iio-widgets/src/guistrategy/comboguistrategy.cpp, iio-widgets/src/guistrategy/editableguistrategy.cpp, iio-widgets/src/guistrategy/rangeguistrategy.cpp, iio-widgets/src/guistrategy/switchguistrategy.cpp, iio-widgets/src/iiowidget.cpp, plugins/debugger/src/iioexplorer/iiostandarditem.cpp
The Data and UI strategy from the IIOWidget are not QObjects, not QWidgets. The LAZY_LOAD function from the IIOWidget now contains only the initial read operation, the setup is done in the constructor.
=> iio-widget: Fix parentless IIOWidgets

plugins/adc/src/adcinstrumentcontroller.cpp, plugins/adc/src/adcinstrumentcontroller.h, plugins/adc/src/adcplugin.cpp
Fixed bugs on ADC instrument : 
1) remove tool button will now not be available in first time and fft tool 
2) adding a new tool bug where add will always add a time tool
=> Adc delete tool bug fix

ci/macOS/install_macos_deps.sh
- reason: brew contains a broken download link for this lib and fails to install it
=> ci/macos: remove libtool installation on macOS12

plugins/adc/src/adcfftinstrumentcontroller.cpp, plugins/adc/src/adcinstrument.cpp, plugins/adc/src/adcinstrument.h, plugins/adc/src/adcplugin.cpp, plugins/adc/src/adctimeinstrumentcontroller.cpp, plugins/adc/src/measurecomponent.cpp, plugins/adc/src/measurecomponent.h
- Fix ADC plugin compat function by checking if the channel is input besides scan elem.
- Fix overlapping hover menus for cursors and measurements by adding a button group.
=> bugfix: adc bugs on compatible function and hover menu overlap

plugins/m2k/src/old/logicanalyzer/logic_analyzer.cpp
- crashes activeWindow was null and created hoverWidget with no parent
=> M2K: logic analyzer tooltip fix

plugins/adc/src/adcfftinstrumentcontroller.cpp, plugins/adc/src/adcfftinstrumentcontroller.h, plugins/adc/src/adcinstrumentcontroller.cpp, plugins/adc/src/adcinstrumentcontroller.h, plugins/adc/src/adcplugin.cpp, plugins/adc/src/adctimeinstrumentcontroller.cpp, plugins/adc/src/adctimeinstrumentcontroller.h, plugins/m2k/src/m2kplugin.cpp, plugins/m2k/src/old/dmm.cpp, plugins/m2k/src/old/dmm.hpp, plugins/m2k/src/old/network_analyzer.cpp, plugins/m2k/src/old/network_analyzer.hpp, plugins/m2k/src/old/oscilloscope.cpp, plugins/m2k/src/old/oscilloscope.hpp, plugins/m2k/src/old/signal_generator.cpp, plugins/m2k/src/old/signal_generator.hpp, plugins/m2k/src/old/spectrum_analyzer.cpp, plugins/m2k/src/old/spectrum_analyzer.hpp, plugins/pqm/include/pqm/harmonicsinstrument.h, plugins/pqm/include/pqm/rmsinstrument.h, plugins/pqm/include/pqm/waveforminstrument.h, plugins/pqm/src/harmonicsinstrument.cpp, plugins/pqm/src/pqmplugin.cpp, plugins/pqm/src/rmsinstrument.cpp, plugins/pqm/src/waveforminstrument.cpp
In the previous version, only the name of the resource was used, which caused some problems when we had multiple devices connected. The resource was opened from one device and closed from another, for example.
=> resourcemanager: Append device uri to resource name.

gui/src/widgets/menucollapsesection.cpp, gui/src/widgets/menusectionwidget.cpp
The menu is collapsed when the header is not checked. 
Collapse Checkbox must be handled as any other checkbox. (arrow)
=> gui/menusectioncollapsewidget: Changed the handling of the header.

.github/contributing/project-structure.md, .github/workflows/license-header.yml, core/include/core/deviceautoconnect.h, core/src/deviceautoconnect.cpp, plugins/m2k/m2k-gui/include/m2k-gui/qtgui_types.h, plugins/m2k/m2k-gui/src/oscilloscope_plot.cpp, plugins/m2k/src/old/frequency_compensation_filter.h, plugins/m2k/src/old/frequency_compensation_filter_impl.cc, plugins/m2k/src/old/frequency_compensation_filter_impl.h, plugins/pqm/include/pqm/pqmdatalogger.h, plugins/pqm/src/pqmdatalogger.cpp, tools/exclude_list.sh, tools/license-header/add_license_header.sh, tools/license-header/batch_add_license_headers.sh, tools/license-header/scan_missing_headers.sh, tools/license.sh
- **CI Job**: Adds a step that fails if files not excluded by the default filters lack a valid Scopy license header as defined in `tools/license-header/templates/Scopy/LICENSE`.
- **Utility**: Introduces `tools/license.sh`, a script that scans the repository for missing license headers, adds them based on file extensions, and supports a verbose mode for detailed output and troubleshooting.
If the CI step fails due to missing headers, run the `./tools/license.sh` utility to fix the missing headers locally. Then, commit and push the changes.
**NOTE:** The utility will also run `./tools/format.sh` automatically.
=> CI: Enforce license headers in source files 

CMakeLists.txt
This option allows users to build the application faster then normally. It works by caching the object files in `${HOME}/.cache/ccache` the first time c/c++ file is compiled so that the next time the file is encountered (e.g. during a clean build) it can just copy the cached object file, instead of compiling it again. This provides a very significant speedup to the build process. Read more: https://ccache.dev/
This feature will not work just by having this commit, you also have to install the `ccache` program (e.g. apt install). It will not work on the CI builds for Scopy (it would be useless there anyways). To clean the cache memory you can just run `ccache -C`. If you do not want this feature at all, uninstalling `ccache` will suffice. 
On this branch, install the `ccache` program and …
=> Add optional fast compile using ccache

src/logicanalyzer/annotationcurve.cpp
- Handle the edge case where an empty string passed to the shortenAnnotationText function causes an infinite loop.
- This fix ensures that the function returns the extension ("...") when the text is empty or the maxWidth is too small to fit the extension.
=> logic analyzer: fix annotation empty string causing infinite loop

plugins/m2k/m2k-gui/sigrok-gui/src/annotationcurve.cpp
- Apply bugfix commit 619458f9b50a2bbaf54f65d2c74a8680425391ac from main to dev
=> logic analyzer: fix annotation empty string causing infinite loop (apply fix to dev)

core/src/licenseoverlay.cpp, gui/include/gui/tintedoverlay.h, gui/include/gui/widgets/popupwidget.h, gui/src/tintedoverlay.cpp, gui/src/widgets/popupwidget.cpp, gui/src/widgets/toolbuttons.cpp
- added function to automatically center on parent widget
=> Popup and overlay update on parent resize

core/src/devicemanager.cpp
If the device was saved as selected for auto-connection from a previous session but the same device is also detected during scanning, the browser will have duplicate entries of the same device, allowing us to connect to both. This should not be possible in most cases: the best example is the ADALM2000 USB connection.
=> core: check if the uri already exists when adding a new device in browser

plugins/m2k/src/old/patterngenerator/patterns/patterns.cpp
Before v2, SmallOnOffSwitch was a QPushButton and emitted the clicked signal. Now it is a QCheckBox and the toggled signal should be used instead.
=> plugins/m2k: fix patterns toggled signal after changing to QCheckBox type.

plugins/debugger/include/debugger/watchlistview.h, plugins/debugger/src/iioexplorer/iioexplorerinstrument.cpp, plugins/debugger/src/iioexplorer/watchlistview.cpp
The 'x' button from the title path was did not update when the object was deleted from the WatchListView, only when clicking the item again.
=> iioexplorer/watchlistview: Fix remove button not updating

.github/workflows/generate_doc.yml, core/src/scopypreferencespage.cpp, docs/extract_macros.py, docs/user_guide/preferences.rst, docs/user_guide/preferences_table.rst, gui/include/gui/preferenceshelper.h, gui/src/preferenceshelper.cpp, pluginbase/include/pluginbase/preferences.h, pluginbase/src/preferences.cpp, plugins/adc/src/adcplugin.cpp, plugins/datalogger/src/dataloggerplugin.cpp, plugins/debugger/src/debuggerplugin.cpp, plugins/m2k/src/m2kplugin.cpp, plugins/regmap/src/regmapplugin.cpp, plugins/test/src/testplugin.cpp, tools/plugingenerator/templates/pdk/pdk_src_template.mako
- Added an info button to display extra details in each preference.
- Create preferences using a macro.
- Scan for the macro when generating documentation and automatically populate it.
- Screenshots on how this looks like: https://github.com/analogdevicesinc/scopy/pull/1884
=> preferences: add description to preferences and autogenerate the docs

tools/style_generator.py
This should fix the style generation script on windows for users.
We did not encounter this issue since we are using MSYS2 to build on windows.
=> Style script fix platform dependent path separator

docs/plugins/dac/dac.rst, docs/tests/plugins/dac/dac_tests.rst, plugins/dac/res/tutorial_chapters.json, plugins/dac/src/bufferdacaddon.cpp, plugins/dac/src/bufferdacaddon.h, plugins/dac/src/dacdatamodel.cpp, plugins/dac/src/dacdatamodel.h
For devices with multiple channels this option will allow the user
to use the same input .csv file for a dynamic number of channels,
without having to duplicate the number of columns in the file.
=> plugins/dac: add a switch to repeat the file buffer for all channels 

plugins/swiot/src/ad74413r/ad74413r.cpp, plugins/swiot/src/max14906/max14906.cpp
https://github.com/analogdevicesinc/scopy/issues/1946
- The plots from the MAX14906 loose the background style when detached
- In the AD74413R tool, if the run button is pressed and a new channel is enabled, the acquisition stops, but the text from the run button still prints "Stop" indicating it is running. The button should just be reset when the acquisition stops.
https://github.com/analogdevicesinc/scopy/issues/1905
=> Issues fixes and minor style adjustments

core/include/core/emuwidget.h, core/include/core/scopypreferencespage.h, core/src/emuwidget.cpp, core/src/scopymainwindow.cpp, core/src/scopypreferencespage.cpp
Some changes have been made in the path finding process.
1. Preference path initialization:
- The iio_emu_dir_path preference is now initialized with an empty value. This allows users to manually specify a custom path to the iio-emu executable, which may be located outside the default Scopy executable directory. If the preference is left empty or the file does not exist, the next verification will be performed.
2. Scopy executable directory search:
- If no valid path is provided in the preferences, we will check for the iio-emu executable in the same directory as the Scopy executable.
3. System search:
- If the iio-emu executable is not found in the Scopy executable directory, a system search is performed.
=> core/emu: Fix emu path bug.

core/include/core/emuwidget.h, core/src/emuwidget.cpp
This is useful on systems where the default port is already in use, allowing the iio-emu to run on a different port. This happens on a Kuiper with the local backend enabled.
=> emu: add a port selector in the EmuWidget.

gui/src/style.cpp, gui/src/stylehelper.cpp, gui/src/widgets/hoverwidget.cpp, gui/style/qss/generic/global.qss
This also fixes admt tests crash since no theme is loaded when running tests and StyleHelper is used
=> GUI: avoid crash on getChannelColor if theme is not initialized

plugins/m2k/src/old/signal_generator.cpp, plugins/m2k/src/old/signal_generator.hpp
In different scenarios, the channel combination can generate a zero ratio when computing the resampling preview parameters. One example is having a buffer source for both channels and configuring 1kHz and 5MHz. This configuration can also be tested using the stairstep waveform.
Add a plot status informing the user that the preview is no longer updated in these scenarios and make sure the gnuradio flow is properly updated.
=> m2k: fix the display resample in scenarios with ratio = 0

plugins/m2k/src/old/signal_generator.cpp
Due to libmatio not being installed in the currently built dockers.
=> m2k: disable MATLAB file support in the siggen for this release.

gui/style/qss/generic/global.qss
The background color of QAbstractItemView did not align with the application theme.
=> style/qss/generic/global: Added QAbstractItemView style.

iio-widgets/include/iio-widgets/guistrategy/checkboxguistrategy.h, iio-widgets/include/iio-widgets/iiowidget.h, iio-widgets/include/iio-widgets/iiowidgetbuilder.h, iio-widgets/src/guistrategy/checkboxguistrategy.cpp, iio-widgets/src/iiowidget.cpp, iio-widgets/src/iiowidgetbuilder.cpp
- Expose controls for changing the visibility of the IIO Widget progress bar.
- Check for {requested_attr}_available in the buildSingle function. This is done when buildAll is called for any type of IIO object, but it could make things simpler if it would also scan this when building a single widget.
- Add a new CheckBox GUI Strategy. It is now visually represented by a SmallMenuOnOffSwitch. It should only be used for boolean values. The previously mentioned control over progress bar visibility is implemented for this.
=> IIO Widgets: multiple changes on iio widgets controls

plugins/debugger/src/iioexplorer/iiomodel.cpp
For some IIO devices, such as iio-sysfs-trigger, the name is missing which is causing crashes during code generation, due to the fact that the entire instrument assumes that all devices have names.
This is a quick workaround. A different approach on these devices is needed, but postponed for now.
=> debugger: make sure iiomodel checks if the device name is empty.

plugins/debugger/src/iioexplorer/iioexplorerinstrument.cpp
In some cases the saved value from the splitter will be 0, causing it to hide some sections. This would be the normal behaviour, but sometimes when the ini file does not exist, the initial value is 0.
=> iioexplorer: Fix splitter sizes

plugins/datalogger/src/menus/datamonitorsettings.cpp
Autoscale is enabled by default but user was able to manually change values.
=> datalogger: fix autoscale enabled bug

ci/windows/scopy-64.iss.cmakein
Hello!
I work for an institution where we use Scopy. We need Scopy installed on a fleet of machines, installed for All users. However, this is not supported as PrivilegesRequiredOverridesAllowed is not currently set in [Setup], which is required by the /ALLUSERS command line parameter for the installer
See:
https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed
My proposed changes would allow users to use the /ALLUSERS flag successfully, as well as have the dialog option to install in administrative (all user) mode.
=> Allow Privilege Override to support All Users installs

ci/macOS/install_macos_deps.sh, ci/macOS/macos_config.sh
- Boost.System lib, needed by GNU Radio, was removed in the 1.89 release
=> ci/macos: lock boost version to 1.85
