analogdevicesinc/scopy

src/network_analyzer.cpp, src/network_analyzer.hpp, src/signal_generator.cpp, src/signal_generator.hpp
=> NetworkAnalyzer SignalGenerator: Handle DAC amplifier powerdown

src/power_controller.cpp
Enable/Disable both ADC input amplifiers.
Enable/Disable the ADF4360 global clock.
All this code should be moved into a HW class / lib M2k.
=> PowerController: Temporarily add miscellaneous HW init

src/homepage_controls.cpp, src/homepage_controls.h, src/stacked_homepage.cpp, src/stacked_homepage.h, src/tool_launcher.cpp, src/tool_launcher.hpp, ui/homepage_controls.ui, ui/tool_launcher.ui
Implemented the following feature: https://github.com/analogdevicesinc/scopy/issues/308
=> Custom homescreen

src/pg_patterns.cpp, src/signal_generator.cpp, src/spinbox_a.cpp, src/spinbox_a.hpp, ui/signal_generator.ui
In the Signal Generator tool you can now use seconds for phase too.
Signed-off-by: Septimiu Sarca <Septimiu.Sarca@analog.com>
=> Phase can be changed into seconds now in Signal Generator tool.

src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/channel_widget.cpp, src/channel_widget.hpp, src/osc_export_settings.cpp, src/osc_export_settings.h, src/osc_import_settings.cpp, src/osc_import_settings.h, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp
This pull request implements the following feature: https://github.com/analogdevicesinc/scopy/issues/89
=> Osc reference waveform

resources/stylesheets/global.qss, src/cursor_readouts.cpp, src/cursor_readouts.h, src/dbgraph.cpp, src/dbgraph.hpp, src/network_analyzer.cpp, src/network_analyzer.hpp, src/oscilloscope.cpp, src/plotpickerwrapper.cpp, src/plotpickerwrapper.h, ui/cursor_readouts.ui, ui/network_analyzer.ui
=> Network analyzer cursors

src/signal_generator.cpp, src/signal_generator.hpp, src/spinbox_a.cpp, src/spinbox_a.hpp, ui/signal_generator.ui
The phase is behaving normally when the channel is changed. 
The value is consistent and so it's the unit measure.
=> Phase available in seconds

src/signal_generator.cpp, src/spinbox_a.cpp, src/spinbox_a.hpp
Signal Generator: Now the frequency value is updated in phase, every time it changes.
Signed-off-by: Septimiu Sarca <Septimiu.Sarca@analog.com>
=> Signal Generator - Fix phase after scopy reset

src/spinbox_a.cpp
When the fine mode is selected the step was changed to 1 degree.
Signed-off-by: Septimiu Sarca <Septimiu.Sarca@analog.com>
=> SignalGenerator: the step for phase when in seconds is 45 degrees

src/apiobjectmanager.cpp, src/apiobjectmanager.h, src/network_analyzer.cpp, src/network_analyzer.hpp, src/oscilloscope.cpp, src/power_controller.cpp, src/power_controller.hpp, src/signal_generator.cpp, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, src/spinbox_a.cpp, src/spinbox_a.hpp, src/tool_launcher.cpp, src/trigger_settings.cpp, src/trigger_settings.hpp, ui/network_analyzer.ui, ui/powercontrol.ui, ui/spectrum_analyzer.ui, ui/trigger_settings.ui
Save / restore functionality for the spin boxes, also fixes issue: https://github.com/analogdevicesinc/scopy/issues/331
=> Spinbox api

src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/dbgraph.cpp, src/dbgraph.hpp, src/filemanager.cpp, src/filemanager.h, src/logic_analyzer.cpp, src/network_analyzer.cpp, src/network_analyzer.hpp, src/osc_export_settings.cpp, src/osc_export_settings.h, src/oscilloscope.cpp, src/oscilloscope.hpp, src/pg_patterns.cpp, src/pg_patterns.hpp, src/signal_generator.cpp, src/signal_generator.hpp, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, ui/network_analyzer.ui, ui/spectrum_analyzer.ui
Added export/import functionality for other tools.
=> Export import rework

src/power_controller.cpp, src/power_controller.hpp
Add properties for enabling/disabling the power supplies via scripts.
Signed-off-by: AntoniuMiclaus <antoniu.miclaus@analog.com>
=> PowerSupply: Add properties for enable/disable

src/DisplayPlot.cc, src/DisplayPlot.h, src/graticule.cpp, src/graticule.h, src/oscilloscope.cpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/preferences.cpp, src/preferences.h, ui/preferences.ui
Implemented https://github.com/analogdevicesinc/scopy/issues/12
=> Oscilloscope graticule

src/dbgraph.cpp, src/dbgraph.hpp, src/network_analyzer.cpp, src/network_analyzer.hpp, src/nyquistGraph.cpp, src/nyquistGraph.hpp, ui/network_analyzer.ui
Implemented https://github.com/analogdevicesinc/scopy/issues/405
=> NetworkAnalyzer: add option to set the line thickness

src/dbgraph.cpp, src/dbgraph.hpp, src/network_analyzer.cpp, src/network_analyzer.hpp, ui/network_analyzer.ui
Signed-off-by: Claudiu Pop <Claudiu.Pop@analog.com>
=> NetworkAnalyzer: added cursors settings

src/DisplayPlot.cc, src/DisplayPlot.h, src/FftDisplayPlot.cc, src/TimeDomainDisplayPlot.cc, src/logic_analyzer.cpp, src/network_analyzer.cpp, src/oscilloscope.cpp, src/printableplot.cpp, src/printableplot.h, src/spectrum_analyzer.cpp, ui/logic_analyzer.ui, ui/network_analyzer.ui, ui/oscilloscope.ui, ui/spectrum_analyzer.ui
Print functionality for the oscilloscope.
=> Osc print plot

src/dbgraph.cpp, src/dbgraph.hpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, ui/cursors_settings.ui
Implemented tracking + locking for the cursors of the oscilloscope.
=> Cursors track mode

src/detachedWindow.cpp, src/detachedWindow.hpp, src/stacked_homepage.cpp, src/tool_launcher.cpp, src/tool_launcher.hpp
Save/ Load the state of a detached tool(position on screen, minimized, maximized)
=> Save detached tools

resources/icons/ic printer.svg, resources/resources.qrc, src/logic_analyzer.cpp, src/printableplot.cpp, ui/logic_analyzer.ui, ui/network_analyzer.ui, ui/oscilloscope.ui, ui/pattern_generator.ui, ui/spectrum_analyzer.ui
Small UI changes regarding the print functionality of some tools.
=> Print icon

resources/stylesheets/global.qss, src/buffer_previewer.cpp, src/buffer_previewer.hpp, src/logic_analyzer.cpp, src/logic_analyzer.hpp, src/osc_custom_scroll.cpp, src/oscilloscope.cpp, src/oscilloscope.hpp, ui/logic_analyzer.ui, ui/measure_panel.ui
Implemented feature: https://github.com/analogdevicesinc/scopy/issues/459
=> Buffer preview scrolling

src/logic_analyzer.cpp
See https://github.com/analogdevicesinc/scopy/issues/522
=> Fix broken Export to VCD in Logic Analyzer

src/filemanager.cpp
Signed-off-by: gotcha france <gotchafr@wanadoo.fr>
=> Fix trailing comma/tab (separator) in FileManager performWrite

.travis.yml, CI/travis/before_install_darwin.sh, CI/travis/before_install_lib.sh, CI/travis/before_install_linux.sh, CI/travis/inside_centos_docker.sh, CI/travis/inside_ubuntu_docker.sh, CI/travis/inside_ubuntu_flatpak_docker.sh, CI/travis/lib.sh, CI/travis/make.sh, CI/travis/make_darwin.sh, CI/travis/make_linux.sh, CI/travis/package_darwin.sh, CMakeLists.txt
Updated dependecies for travis and also added a docker build for ubuntu 18.04 (bionic).
=> Fix travis 

src/DisplayPlot.cc, src/DisplayPlot.h, src/HistogramDisplayPlot.cc, src/HistogramDisplayPlot.h, src/TimeDomainDisplayPlot.cc, src/extendingplotzoomer.cpp, src/histogram_sink_f_impl.cc, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_api.cpp, src/oscilloscope_api.hpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/preferences.cpp, src/preferences.h, ui/osc_general_settings.ui, ui/oscilloscope.ui, ui/preferences.ui
Implements feature: https://github.com/analogdevicesinc/scopy/issues/463
=> Osc histogram plot

resources/icons/gate_handle.svg, resources/resources.qrc, src/buffer_previewer.cpp, src/buffer_previewer.hpp, src/handles_area.cpp, src/handles_area.hpp, src/measure.cpp, src/measure.h, src/measure_settings.cpp, src/measure_settings.h, src/oscilloscope.cpp, src/oscilloscope.hpp, src/oscilloscope_api.cpp, src/oscilloscope_api.hpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/plot_line_handle.cpp, src/plot_line_handle.h, src/symbol.cpp, src/symbol.h, ui/measure_settings.ui
Implements https://github.com/analogdevicesinc/scopy/issues/310
=> Oscilloscope: Measurement gating

src/DisplayPlot.cc, src/TimeDomainDisplayPlot.cc, src/oscilloscope_plot.cpp
Fix some memory leaks in various plots.
=> Memory leak fix

src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/oscilloscope.cpp, src/smoothcurvefitter.cpp, src/smoothcurvefitter.h, ui/channel_settings.ui
This pr implements feature: #529
=> Osc plot modes

src/la_channel_manager.cpp, src/la_channel_manager.hpp, src/logic_analyzer_api.cpp, src/logic_analyzer_api.hpp, src/pattern_generator_api.cpp, src/pattern_generator_api.hpp, src/pulseview/pv/prop/property.cpp, src/pulseview/pv/prop/property.hpp
=> LogicAnalyzer: save decoder settings to .ini

src/measure.cpp
=> measure.cpp: dangling-else warning & added parantheses

src/la_channel_manager.cpp, src/la_channel_manager.hpp, src/logic_analyzer.cpp
=> treewide: YABoFW: yet another batch of fixed warnings

src/measure.cpp, src/oscilloscope.cpp
=> src/measure.cpp: fix number of samples count when gating is enabled

src/oscilloscope.cpp
=> src/oscilloscope.cpp: disable labels only if no channel is found

src/spinbox_a.cpp
=> SpinBoxA: don't allow scrolling through values when disabled

appveyor.yml
Signed-off-by: Daniel Guramulta <Daniel.Guramulta@analog.com>
=> Install older version of hdf5 and libmatio

src/main.cpp
Add support for 4k displays on windows.
Signed-off-by: Daniel Guramulta <Daniel.Guramulta@analog.com>
=> Windows 4k support

src/oscilloscope.cpp, ui/channel_settings.ui
=> Osc: implement snapshot functionality

src/signal_generator.cpp
=> Signal Generator: Check if any file is selected before trying to load it.

src/la_channel_manager.cpp
=> LogicAnalyzer: channel manager will maintain selected state on update_ui

src/spinbox_a.cpp
=> PhaseSpinButton: fix issue when focusing out the widget

src/spinbox_a.cpp
=> src/spinbox_a.cpp: fix logic error

src/hardware_trigger.cpp, src/hardware_trigger.hpp, src/logic_analyzer.cpp, src/logic_analyzer.hpp, src/logic_analyzer_api.cpp, src/logic_analyzer_api.hpp, src/oscilloscope_api.cpp, src/oscilloscope_api.hpp, src/trigger_settings.cpp, src/trigger_settings.hpp, ui/digital_trigger_settings.ui, ui/trigger_settings.ui
With the new firmware, support for trigger out and cross instrument triggering is added. This pull request makes the necessary changes in Scopy to support that.
=> External triggering 

CMakeLists.txt
=> CMakeLists: Bump to version v1.1.0

src/logic_analyzer.cpp, src/logic_analyzer.hpp, src/trigger_settings.cpp
make sure condition is set to falling edge
=> Trigger: When logic analyzer is selected as external trigger src,

src/tool.cpp
=> Tool: make sure to set the checked state of the run buttons to false

src/filemanager.cpp, src/filemanager.h, src/network_analyzer.cpp, src/oscilloscope.cpp, src/pg_patterns.cpp, src/signal_generator.cpp, src/spectrum_analyzer.cpp
Signal Generator: Handle empty lines in loaded files.
Signal Generator: Handle loading empty files.
Signal Generator: Handle loading .mat, .txt and .wav files.
Network Analyzer, Spectrum Analyzer, Pattern Generator, Oscilloscope: Handle loading multiple file types, not just .csv.
=> General: Fix some file load issues in the entire app, mainly in Signal Generator.

src/pulseview/pv/data/decoderstack.cpp
When running the LogicAnalyzer with multiple groups enabled, each having a
decoder active, Scopy would freeze and never recover. The problem is that
each instance of DecoderStack (the class that manages decoding) spawns a
thread that would lock a global mutex for the access to libsigrokdecode.
When this decoders are stopped if the thread that currently owns access to
libsigrokdecode is not joined first, the freeze occurs as there is no way
to interrupt that thread from waiting to acquire the mutex, while also not
having a way to interrupt the thread that acquired the mutex. To fix this
we allow each thread to defer the mutex while only one of them gets to own
it at a time. When the threads are now joined, they will stop trying to
acquire the mutex and exit peacefully.
Signed-off-by: …
=> Logic Analyzer: fix blocking when running

CMakeLists.txt, resources/english.ts, src/connectDialog.cpp, src/customSwitch.cpp, src/device_widget.cpp, src/digitalio.cpp, src/dmm.cpp, src/logic_analyzer.cpp, src/main.cpp, src/measure_settings.cpp, src/network_analyzer.cpp, src/network_analyzer_api.cpp, src/osc_export_settings.cpp, src/osc_import_settings.cpp, src/oscilloscope.cpp, src/oscilloscope_plot.cpp, src/pattern_generator.cpp, src/pg_patterns.cpp, src/preferences.cpp, src/preferences.h, src/signal_generator.cpp, src/sismograph.cpp, src/spectrum_analyzer.cpp, src/startstoprangewidget.cpp, src/tool_launcher.cpp, src/user_notes.cpp, ui/preferences.ui
=> General: Add languages/translation support

CMakeLists.txt, appveyor.yml
=> Fix appveyor

CI/appveyor/build_appveyor_mingw.sh, CI/appveyor/install_msys_deps.sh, CI/appveyor/set_build_env_msys.sh, CMakeLists.txt, appveyor.yml, src/signal_generator.cpp
=> CI: fixed appveyor issues for Windows builds

.github/workflows/dockerimage.yml, CI/appveyor/inside_flatpak_docker.sh
Create dockerimage.yml and use Github Actions to build a Scopy.flatpak in a clean Docker container.
=> Github Actions: Create dockerimage.yml and use Github Actions.

CI/appveyor/before_install_lib.sh, CI/appveyor/build_appveyor_macos.sh, CI/appveyor/install_macos_deps.sh, CI/appveyor/package_darwin.sh, appveyor.yml
=> appveyor.yml: Add macOS 10.15 and 10.14 build on appveyor and deploy Scopy.dmg.

appveyor.yml, src/dmm.cpp, src/dmm.hpp, src/dmm_api.cpp, src/dmm_api.hpp, ui/dmm.ui
Rewrote the flow so there is no need for two AC modes. Also reduced CPU usage(by lowering the sample rate) and improved stability by using a moving average in the end of the flow.
=> Fix DMM measurement

src/logicanalyzer/logic_analyzer.cpp, src/preferences.cpp, src/signal_generator.cpp, src/signal_generator.hpp, src/signal_generator_api.cpp, src/signal_generator_api.hpp, src/spinbox_a.cpp, src/spinbox_a.hpp, ui/math.ui, ui/preferences.ui, ui/signal_generator.ui
https://github.com/analogdevicesinc/scopy/issues/821
https://github.com/analogdevicesinc/scopy/issues/819
=> Signal Generator math/wave/stairstep update

src/logicanalyzer/logic_analyzer.cpp, ui/logic_analyzer.ui
Display a warning if the firmware is too old for this feature.
This ensures backwards compatibility for this version of Scopy using
older firmware versions.
=> Logic Analyzer: Check if the firmware version is capable of using the External Trigger for the logic analyzer.

CI/appveyor/build_appveyor_mingw.sh, scopy-32.iss.cmakein, scopy-64.iss.cmakein, scopy.iss.cmakein
=> WindowsInstaller: Added checkbox that deletes Scopy.ini

src/oscilloscope.cpp
Disable mixed signal view when using an incompatible firmware.
=> Oscilloscope: Disable mixed signal view.

src/calibration.cpp, src/calibration.hpp, src/info_page.cpp, src/info_page.hpp, src/main.cpp, src/preferences.cpp, src/preferences.h, src/scopyExceptionHandler.h, src/tool_launcher.cpp, src/tool_launcher.hpp, ui/info_page.ui, ui/preferences.ui
This PR requires libm2k with isCalibrated() method implemented.
=> Skip cal if already cal

src/trigger_settings.cpp
Bug description: The analogical source did not return to its normal state after disabling the digital source.
=> trigger_settings: Fix trigger source after disabling external trigger.

CMakeLists.txt
=> CMakeLists.txt: bump to v1.2.0

src/logicanalyzer/logicdatacurve.cpp, src/patterngenerator/pattern_generator.cpp, src/patterngenerator/patterns/patterns.cpp, src/patterngenerator/patterns/patterns.hpp, src/runsinglewidget.cpp, src/tool_launcher.cpp, src/tool_launcher.hpp
Fixes for the following bugs
- #875 
- #876 
- #877 
- #880 
- #881 
- #882
Also the calibration thread was playing with the GUI sometimes causing weird crashes while drawing and polishing widgets. GUI stuff should be only handled from the main thread. Added a fix with: b98dc15.
=> Release fixes

CMakeLists.txt, src/dmm.cpp, src/logicanalyzer/logic_analyzer.cpp, src/spectrum_analyzer.cpp, src/tool_launcher.cpp, ui/dmm.ui, ui/logic_analyzer.ui
- LogicAnalyzer: fix external trigger condition
- Remove unused includes
- CMakeLists.txt: properly find and link libm2k
=> more fixing

src/mixed_signal_sink.h, src/mixed_signal_sink_impl.cpp, src/mixed_signal_sink_impl.h, src/oscilloscope.cpp
=> MixedSignalView: fix plotting issue when timebase is >= 100ms

src/oscilloscope_plot.cpp
=> CapturePlot: fix loading of groups

src/trigger_settings.cpp
Bug description: switching between auto and normal mode, the normal mode would eventually result to behave as the auto mode.
=> TriggerSettings: Fix normal mode.

src/signal_generator.cpp
=> SignalGenerator: Remove useless instrument output

src/FftDisplayPlot.cc, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, src/startstoprangewidget.cpp, src/startstoprangewidget.h
- Fix bug #899 with commit 13bec282608113233a538c6ce1cf02a3c26a311f
- Fix bug #900 with commit e78efb42dd1d46713160e4ccffe1830e9e0572e1
- Allow the Frequency to be zero
=> Release candidate: Fixes for the Spectrum analyzer

CI/appveyor/extract_msys_deps.sh, CI/appveyor/install_msys_deps.sh
=> appveyor: Forgot to change scopy-mingw-build-deps branch back to master.

ui/runsinglewidget.ui
=> RunSingleWidget: change icon if single / run button is checked

src/patterngenerator/pattern_generator.cpp
=> PatternGenerator: don't show trigger state as it makes no sense now

ui/preferences.ui
=> Preferences: specify required version for skip calibration preference

resources/translations/scopy_de.ts
=> resources: translations: scopy_de.ts: Add German translation

CMakeLists.txt, resources/translations.qrc
=> CMakeLists.txt: generate translations resource file from TS_FILES

src/tool_launcher.cpp
This handles the crashes that might happen if the board is unplugged during connection, right before starting the calibration.
This commit also changes a bit, the flow of the connection:
- We stop the Search Timer before creating the context. We create the context, handle any issues that might appear, without worrying that the Search Timer will remove an M2K from the list while we did not manage to uninit everything related to it.
- Start the Alive Timer after every tool was properly initialized and contructed, not after the iio_context creation. A lot of exceptions can raise between constructing the iio_context and finishing up all the Tools.
- Disconnect if anything failed during the "switchContext" phase (which created the iio_context and all the tools). The disconnect phase will …
=> Tool Launcher: Handle possible exceptions thrown from tools that don't require calibration.

src/singletone_wrapper.h, src/spinbox_a.cpp, src/tool_launcher.cpp
Should fix the issue described in: #955
@adisuciu can you test this with the same method you used to find out about this issue and see if there are any improvements?
=> Settings saving performance

resources/translations/scopy_es.ts
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
=> resources: translations: Add Spanish translation

src/dmm.cpp, src/dmm.hpp, src/dmm_api.cpp, src/dmm_api.hpp, ui/dmm.ui
Implements feature described in #940
=> Voltmeter manual range

resources/translations/scopy_it.ts
translated by Rocco Marco Guglielmi
=> languages: added italian

resources/translations/scopy_jp.ts
Translated by Jun Kakinuma, Hiroshi Ishida, Miki Tsuboi
=> languages: added japanese

resources/translations/scopy_kr.ts
Translated by Perry Kwon and Steven Yang
=> languages: added korean

src/calibration.cpp, src/calibration.hpp, src/info_page.cpp, src/info_page.hpp, src/preferences.cpp, src/tool_launcher.cpp, ui/info_page.ui
=> Calibration: Implement temperature lookup-table based calibration

resources/translations/scopy_ar.ts
translated by Amr Sherief and Ahmed Khalil
=> languages: added egyptian arabic

resources/translations/scopy_th.ts
Translated by Sopon Prommachai
=> languages: added thai

resources/translations/scopy_tw.ts
=> languages: added traditional chinese

src/logicanalyzer/logic_analyzer.cpp, src/logicanalyzer/logic_analyzer.h, src/logicanalyzer/logicdatacurve.cpp, src/oscilloscope_plot.cpp, ui/logic_analyzer.ui
=> Logic small fixes

scopy2.0/CMakeLists.txt, scopy2.0/cmake/doxygen.cmake, scopy2.0/cmake/readme.md
=> Add doxygen to the project

src/info_page.cpp, src/info_page.hpp, src/session_info.cpp, src/session_info.h, src/tool_launcher.cpp, src/tool_launcher.hpp, src/tool_launcher_api.cpp
=> ToolLauncher: report a bug now points to the wiki

scopy2.0/cmake/readme.md, scopy2.0/doc/readme.md
=> cmake: update readme.md

scopy2.0/doc/readme.md
=> Doc: Updated README.md

scopy2.0/app/mainwindow.cpp, scopy2.0/gui/CMakeLists.txt, scopy2.0/gui/include/scopy/gui/settings_pair_widget.hpp, scopy2.0/gui/resources/stylesheets/global.qss, scopy2.0/gui/src/custom_push_button.cpp, scopy2.0/gui/src/custom_push_button.hpp, scopy2.0/gui/src/settings_pair_widget.cpp, scopy2.0/gui/ui/settings_pair_widget.ui
=> Custom Widgets: Added SettingsPairWidget

CI/appveyor/install_msys_deps.sh
=> ci: windows: install libusb v1.0.21

src/oscilloscope.cpp, src/tool_launcher.cpp, ui/cursors_settings.ui, ui/network_analyzer.ui, ui/osc_general_settings.ui, ui/powercontrol.ui, ui/spectrum_analyzer.ui
=> Ui: Added scroll areas where needed

src/preferences.cpp, src/scopy_color_editor.cpp
This will allow the user to browse and apply a custom stylesheet that is not included with scopy
=> Preferences: allow the user to browse for a custom stylesheet

src/homepage_controls.cpp, src/info_page.cpp, src/info_page.hpp, ui/info_page.ui
=> InfoPage: added device registration link

cmake/staticAnalyzers.cmake
=> StaticAnalysis: add shellcheck for sh files

ui/cursors_settings.ui, ui/digitalio.ui, ui/network_analyzer.ui, ui/spectrum_analyzer.ui
=> Fixed widgets spacing in 4k

src/spectrum_analyzer.cpp
=> SpectrumAnalyzer: don't force scale/div to 1

CI/appveyor/build_appveyor_mingw.sh
=> ci: disable dll & executable stripping

core/CMakeLists.txt, core/include/scopy/core/context_enumerator.hpp, core/src/context_enumerator.cpp, gui/include/scopy/gui/tool_launcher.hpp, gui/src/tool_launcher.cpp, gui/ui/tool_launcher.ui
=> Tool Launcher: Added BoardDetector

ui/digitalIoElement.ui
=> DigitalIoElement: fix initial settings

src/oscilloscope_plot.cpp
=> CapturePlot: fix index of new handles

gui/include/scopy/gui/preferences.hpp, gui/src/menu_anim.cpp, gui/src/menu_anim.hpp, gui/src/tool_launcher.cpp
=> Added missing files

src/main.cpp
Work in progress for a fix to solve a bug that is causing: #1088 
=> main.cpp: instantiate ToolLauncher after setting the application theme

src/logicanalyzer/logic_analyzer.cpp, ui/cursors_settings.ui
=> Logic Analyzer: Removed spacers from Cursors menu

src/logicanalyzer/logic_analyzer.cpp
Signed-off-by: Adrian Suciu <adrian.suciu1988@gmail.com>
=> LogicAnalyzer: Remove autoappend extension to export filename

CI/appveyor/install_macos_deps.sh
=> macos: Update brew before searching and installing packages.

CI/appveyor/install_macos_deps.sh, CI/appveyor/install_ubuntu_18_deps.sh, CI/appveyor/install_ubuntu_20_deps.sh, src/logicanalyzer/annotationdecoder.cpp, src/logicanalyzer/annotationdecoder.h
- Build latest version of libsigrokdecode.
- Synchronize libsigrok session access.
=> Fix decoding crash

gui/CMakeLists.txt, gui/include/scopy/gui/generic_menu.hpp, gui/include/scopy/gui/subsection_separator.hpp, gui/include/scopy/gui/test_menu.hpp, gui/src/generic_menu.cpp, gui/src/subsection_separator.cpp, gui/src/test_menu.cpp, gui/src/test_tool.cpp, gui/ui/subsection_separator.ui
=> SubsectionSeparator: Added container for its elements

src/tool_launcher.cpp
=> tree: disable digital decoders on Android

src/FftDisplayPlot.cc, src/FftDisplayPlot.h, src/TimeDomainDisplayPlot.cc, src/TimeDomainDisplayPlot.h, src/logicanalyzer/logic_analyzer.cpp, src/oscilloscope.cpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/patterngenerator/pattern_generator.cpp, src/signal_generator.cpp
=> Added changeable units to capture and fft plots

src/tool_launcher.cpp
=> tool_launcher: changed buttons type for initial message box

CI/appveyor/install_ubuntu_18_deps.sh, CMakeLists.txt
=> cmake: fix qwt and gr OOTs find_package / find_library

.github/workflows/androidbuild.yml, CI/appveyor/android-docker/Dockerfile, CI/appveyor/build_scopy_apk.sh
=> ci: configured android build to be performed for current branch

src/connectDialog.cpp
=> iio-emu: use IIOEMU_BIN envvar on all platforms

CMakeLists.txt, resources/stylesheets/templates/default.qss.c, resources/stylesheets/templates/light.qss.c
=> cmake: preprocess stylesheets using clang

src/tool_launcher.cpp
=> tool_launcher: fix decoders load path

CMakeLists.txt
=> ci: enable stylesheets preprocessing on all platforms

src/FftDisplayPlot.cc, src/FftDisplayPlot.h, src/gui/measure.cpp, src/gui/measure.h, src/gui/measure_settings.cpp, src/gui/measure_settings.h, src/measurement_gui.cpp, src/measurement_gui.h, src/oscilloscope.cpp, src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, ui/measure_settings.ui, ui/spectrum_analyzer.ui
=> Spectrum analyzer: added the infrastructure for measurements

src/gui/info_page.cpp, src/tool_launcher.cpp
=> tool_launcher: fix ping function with adequate iio call

src/tool_launcher.cpp
=> src/tool_launcher.cpp: Provide the full path to the decoders location.

appveyor.yml
=> ci: stopped building for macos-mojave start building for macos-bigsur

src/gui/measure.cpp
=> spectral measurements: temporary fix crash

CI/appveyor/install_qt_ubuntu_20.sh, CI/appveyor/install_ubuntu_20_deps.sh
=> install_ubuntu_20.sh: Add missing packages for qwt and sigrokdecode.

src/main.cpp
=> main.cpp: fix compilation error

src/oscilloscope.cpp, src/oscilloscope_api.cpp, ui/channel_settings.ui
Updated Probe Attenuation values to include : 0.2; 0.5; 2; 5; 20; 50; 200; 500
=> Dev probe attenuation

CI/appveyor/before_install_lib.sh, CI/appveyor/build_appveyor_macos.sh, CI/appveyor/install_macos_deps.sh, CI/appveyor/package_darwin.sh, appveyor.yml, azure-pipelines.yml
=> azure-pipelines.yml: Move MacOS builds to Azure Pipelines.

src/gui/externalloadlineedit.cpp, src/gui/externalloadlineedit.h, src/signal_generator.cpp, src/signal_generator.hpp, src/signal_generator_api.cpp, src/signal_generator_api.hpp, ui/signal_generator.ui
https://github.com/analogdevicesinc/scopy/issues/1154
=> SignalGenerator: implemented external load setting

src/gui/channel_manager.cpp, src/gui/channel_manager.hpp, src/gui/custom_menu_button.cpp, src/gui/custom_menu_button.hpp, src/gui/generic_menu.cpp, src/gui/generic_menu.hpp, src/gui/menu_header.cpp, src/gui/menu_header.hpp, src/gui/settings_pair_widget.cpp, src/gui/settings_pair_widget.hpp, src/gui/subsection_separator.cpp, src/gui/subsection_separator.hpp, src/gui/theme_manager.cpp, src/gui/theme_manager.hpp, src/gui/tool_view.cpp, src/gui/tool_view.hpp, src/gui/tool_view_builder.cpp, src/gui/tool_view_builder.hpp, src/oscilloscope.cpp, src/signal_generator.cpp, ui/tool_view.ui
This prevents clash between gr:scopy and scopy namespaces
=> general: change scopy namespace to adiscope

src/BasicPlot.cpp, src/DisplayPlot.cc, src/limitedplotzoomer.cpp, src/limitedplotzoomer.h, src/logicanalyzer/logic_analyzer.cpp, src/oscilloscope_plot.cpp, src/signal_generator.cpp
=> general: make scopy generate less output on connect

src/dmm.cpp, src/iio_manager.cpp, src/iio_manager.hpp
=> dmm: use kernel buffers when using dmm

CMakeLists.txt
=> CMakeLists.txt: Bump to version v1.4.0.

.github/workflows/androidbuild.yml, .github/workflows/linuxflatpakbuild.yml, .github/workflows/mingwbuild.yml, azure-pipelines.yml
Auto push master artifacts to "Continuous build"
=> Continuous integration

src/tool_launcher.cpp
=> Fix ping condition

src/signal_generator.cpp, ui/signal_generator.ui
=> Removed last opened menu button for signal generator

src/digitalio.cpp
=> dio: initialization bug fix

src/patterngenerator/pattern_generator.cpp
=> pattern_generator: plot preview bug fix

src/patterngenerator/pattern_generator.cpp
=> pattern_generator: plot scroll bug fix

src/spectrum_analyzer.cpp
=> spectrum analyzer: Fix typo - "dB" labels on the plot.

src/tool_launcher.cpp
=> general: general menu collapsed after reset bug fix

src/spectrum_analyzer.cpp
=> Spectrum Analyzer: Enable zoom on plot using the existing zoomer mechanism.

src/dmm.cpp
https://github.com/analogdevicesinc/scopy/issues/1257
=> dmm: fix autorange bug

ui/dmm.ui
=> dmm: fix notes label size

src/logicanalyzer/logic_analyzer.cpp, src/logicanalyzer/logic_analyzer.h, src/patterngenerator/pattern_generator.cpp, src/patterngenerator/pattern_generator.h
=> generic: fix pattern generator and logic analyzer print bug

android/AndroidManifest.xml
=> android: bump android version

src/logicanalyzer/logic_analyzer.cpp
=> osc: mixed signal scroll bug fix

src/preferences.cpp
=> preferences: request restart after enabling debug instrument

resources/translations/scopy_ro.ts
=> translation: fixed bad Romanian translation for Single text

resources/stylesheets/templates/default.qss.c, resources/stylesheets/templates/light.qss.c, src/logicanalyzer/logic_analyzer.cpp, src/main.cpp, src/network_analyzer.cpp, src/oscilloscope.cpp, src/patterngenerator/pattern_generator.cpp, src/signal_generator.cpp, src/spectrum_analyzer.cpp, ui/oscilloscope.ui
- commit : 9f2e5897b405be0a60c79be07ae58f148f1cef65 and ecb7c7d4e01f73dfd31fc2ac882d522bdf09eac1 for issue #1270
- commit : 7731c8a04eaf354d2e6c4327052cb88e3e7146a3 for issue #1271
- commit :  af6684ee7ec609e369db4dbfb48e9461893936ec for issue #1268
- commit : f50fac679e84e56f3ddce59c4cc83e4499c94ff4 for issue #1269
- commit dc2337e1c0cad8d7f8ef79e2a718dd665b4948d1 needs to be checked on Windows and Linux (flatpak) to check whether the style change made some damage to the look of the widgets
=> Fix multiple issues related to dockable plots and UI size constraints.

src/network_analyzer.cpp
=> network_analyzer: enable axis labels on Nichols plot

src/oscilloscope_plot.cpp, src/oscilloscope_plot.hpp
=> plot: added label at print for digital curves

src/tool_launcher.cpp, src/tool_launcher.hpp
=> tool_launcher: add license agreement dialog box first time you run Scopy

android/AndroidManifest.xml
=> android: allow both landscape and "upside-down" landscape

android/src/org/adi/scopy/ScopyActivity.java
=> android: fix crash when application pauses before it starts

android/src/org/adi/scopy/ScopyActivity.java
=> android: keep screen on while app is running

src/gui/connectDialog.cpp
=> connectDialog.cpp: Fix program path for iio-emu on Windows builds.

android/src/org/adi/scopy/ScopyActivity.java, src/tool_launcher.cpp, src/tool_launcher.hpp
This prevents the app from acquiring data in the background
=> android: save tool running state before onStop and restore onStart

src/network_analyzer.cpp
=> networkanalyser: decouple iteration computation from GUI update

src/main.cpp, src/preferences.cpp, src/preferences.h
=> android: fix the style for the message boxes

CMakeLists.txt, resources/scopy.desktop.cmakein
=> cmake: fix path for linux icon

ui/oscilloscope.ui
=> oscilloscope: fix top bar buttons spacing

ui/signal_generator.ui
=> siggen: fix weird spacing in ui file

src/logicanalyzer/logic_analyzer.cpp
=> osc and logic analyzer: mixed signal scroll bug fix

src/signal_generator.cpp, ui/signal_generator.ui
=> siggen: fix layout not showing instrument notes

src/patterngenerator/pattern_generator.cpp, src/patterngenerator/pattern_generator.h
=> pattern_generator: fix is_running overwrite bug

appveyor.yml
=> ci: remove ubuntu18 build

src/oscilloscope.cpp
After 200ms/div, the tool enters streaming mode, which makes use of
kernel buffers to acquire data in smaller chunks.
There are 2 scenarios:
-the trigger is inside the visible buffer and the buffer size is
restricted by the trigger value;
-the trigger is 0, which means we get to manipulate the best values
for buffersize and number of kernel buffers.
Also, the time position handle needs some limits when the time base is
over the timebase threshold.
=> src/oscilloscope.cpp: Fix crash in streaming mode.

CMakeLists.txt, src/FftDisplayPlot.cc, src/FftDisplayPlot.h, src/cancel_dc_offset_block.cpp, src/cancel_dc_offset_block.h, src/dmm.cpp, src/dmm.hpp, src/fft_block.cpp, src/frequency_compensation_filter.h, src/frequency_compensation_filter_impl.h, src/gui/measure.cpp, src/histogram_sink_f.h, src/iio_manager.cpp, src/iio_manager.hpp, src/logic_analyzer_sink.h, src/math.cpp, src/mixed_signal_sink.h, src/network_analyzer.cpp, src/network_analyzer.hpp, src/oscilloscope.cpp, src/oscilloscope.hpp, src/scope_sink_f.h, src/signal_generator.cpp, src/spectrum_analyzer.cpp, src/spectrum_analyzer.hpp, src/spectrum_analyzer_api.hpp, src/stream_to_vector_overlap.h, src/xy_sink_c.h
=> Port to gnuradio 3.10

.github/workflows/androidbuild.yml, .gitignore, CI/android/android_deploy_libs.sh, CI/android/android_deploy_qt.sh, CI/android/android_get_symbols.sh, CI/android/android_scopy_keystore, CI/appveyor/build_scopy_apk.sh, android/AndroidManifest.xml, android/build.gradle, android/src/org/adi/scopy/ScopyActivity.java, src/tool_launcher.cpp
This causes a crash on some platforms where onStop is called before
the lifecycle of the app reached ToolLauncher initialization
=> android: google play store fixes

src/filemanager.cpp, src/filemanager.h, src/logicanalyzer/annotationcurve.cpp, src/logicanalyzer/annotationcurve.h, src/logicanalyzer/logic_analyzer.cpp, src/logicanalyzer/logic_analyzer.h, src/preferences.cpp, src/preferences.h, ui/logic_analyzer.ui, ui/preferences.ui
Signed-off-by: Andrei Popa <andrei.popa@analog.com>
=> logic analyzer: export functionality also saves decoder values

CMakeLists.txt
=> CMakeLists.txt: Bump to version v1.4.1.

CI/appveyor/package_darwin.sh
=> CI/appveyor/package_darwin:Update python possible versions on MacOS builds.

src/datalogger/datalogger.cpp, src/datalogger/datalogger.hpp, src/datalogger/datalogger_api.cpp, src/datalogger/dataloggerreaderthread.cpp, src/gui/customcolqgridlayout.cpp, src/gui/dataloggercontroller.cpp, src/gui/dataloggercontroller.hpp, src/gui/dataloggerview.cpp, src/gui/dataloggerview.hpp, src/sismograph.cpp, ui/channelmonitorcomponent.ui
Signed-off-by: Cristian Bindea <cristian.bindea@analog.com>
=> datalogger: bugfix

core/doc/core.qmodel, core/src/deviceimpl.cpp, pluginbase/doc/plugin_lifecycle.qmodel, pluginbase/include/pluginbase/plugin.h, pluginbase/include/pluginbase/pluginbase.h
This would allow the plugin to trigger a connect or a disconnect for that device, which would propagate to all the linked plugins.
=> PluginBase: Add a connectDevice signal to the plugin interface.

core/CMakeLists.txt, core/include/core/deviceloader.h, core/include/core/devicemanager.h, core/include/core/scopy-core_config.h.cmakein, core/src/deviceloader.cpp, core/src/devicemanager.cpp, core/src/scopymainwindow.cpp
A parameter to init() will start device init as sync or async process
=> core: implement sync/async deviceloader and devmode

.github/workflows/ubuntu20build.yml, .github/workflows/ubuntu22build.yml, ci/ubuntu/docker_ubuntu20/Dockerfile, ci/ubuntu/docker_ubuntu22/Dockerfile, ci/ubuntu/install_ubuntu_20_deps.sh, ci/ubuntu/install_ubuntu_22_deps.sh
- added docker recipe for Ubuntu, version 20.04 and 22.04
- modified the Github workflow script so that is uses the docker image
=> Build scopy from docker image on Ubuntu

iioutil/test/tst_iiocommandqueue.cpp
The ideal thread count for some systems might not be enough and threads that were not started yet might reach the thread pool expiry timeout.
=> TST_iiocommandqueue: Fix max thread pool count reaching timeout.

core/doc/core.qmodel, core/doc/device_lifecycle.qmodel
Added the changes for device connection flow and for the add page.
=> Core diagrams update

gr-util/CMakeLists.txt, gr-util/include/gr-util/grtimeplotaddonsettings.h, gr-util/src/grtimeplotaddonsettings.cpp, gr-util/src/grtopblock.cpp
=> gr-util: fix memory leak when rebuilding gr-topblock

core/include/core/scopyaboutpage.h, core/include/core/scopypreferencespage.h, core/src/scopyaboutpage.cpp, core/src/scopymainwindow.cpp, core/src/scopypreferencespage.cpp, gui/include/gui/stylehelper.h, gui/res/stylesheets/default.qss, gui/src/stylehelper.cpp, pluginbase/include/pluginbase/preferences.h, pluginbase/include/pluginbase/preferenceshelper.h, pluginbase/src/preferenceshelper.cpp, plugins/adc/src/adcplugin.cpp, plugins/m2k/src/m2kplugin.cpp, plugins/regmap/src/regmapplugin.cpp, plugins/testplugin/src/testplugin.cpp, plugins/testplugin/src/testtool.cpp
- UI improvement WIP
- restart button fix
=> Preferences fixes

CMakeLists.txt, ci/windows/inside_mingw_docker.sh, cmake/Modules/ScopyWindows.cmake
Create another scopy.exe named scopy-cl.exe that has console output turned on
=> Windows debug

core/src/deviceimpl.cpp, core/src/scopymainwindow.cpp, plugins/debugger/src/debuggerplugin.cpp, plugins/m2k/src/m2kplugin.cpp
Plugins connection/disconnection time monitoring is now done in DeviceImpl. Added more detailed messages.
=> Benchmark: Monitoring changes.

gr-util/include/gr-util/grtimeplotaddon.h, gr-util/include/gr-util/time_sink_f.h, gr-util/include/gr-util/time_sink_f_impl.h, gr-util/src/grtimeplotaddon.cpp, gr-util/src/time_sink_f_impl.cc, gui/include/gui/plotwidget.h, gui/include/gui/widgets/plotinfo.h, gui/src/plotwidget.cpp, gui/src/widgets/plotinfo.cpp
=> gui: create plot info widget

core/src/crashreport.cpp
Prevents app hanging after a crash
=> core: let application run it's course when a signal is handled

plugins/regmap/src/utils.cpp
=> Regmap bug fix

core/include/core/iiotabwidget.h, core/src/iiotabwidget.cpp, core/ui/iiotabwidget.ui, gui/include/gui/stylehelper.h, gui/src/stylehelper.cpp
I created another scan button which is used only for serial devices because the approach for scanning the serial devices is different compared to the others backends.
=> Add page: scan process changes

plugins/m2k/src/m2kplugin.cpp, plugins/m2k/src/old/logicanalyzer/logic_analyzer.cpp
- correctly use ToolMenuEntry to hide run button
- use correct Preferences id
- typo
=> plugins/m2k: minor fixes

gui/include/gui/stylehelper.h, gui/include/gui/widgets/scopystatusbar.h, gui/src/stylehelper.cpp, gui/src/widgets/scopystatusbar.cpp, pluginbase/src/statusbarmanager.cpp, plugins/swiot/include/swiot/swiotplugin.h, plugins/swiot/src/swiotplugin.cpp
It now offers the possibility to display temporary messages over permanent messages.
=> Status bar changes

CMakeLists.txt, gr-util/src/grdeviceaddon.cpp, gr-util/src/grtimechanneladdon.cpp, gr-util/src/grtimeplotaddon.cpp, gr-util/src/grtimeplotaddonsettings.cpp, gui/include/gui/widgets/toolbuttons.h, gui/src/widgets/measurementsettings.cpp, gui/src/widgets/toolbuttons.cpp
=> adc: various fixes

src/logicanalyzer/logic_analyzer.cpp
=> Scopy 1.5: fixed crash when moving ch handles in oscilloscope mixed signal view

tools/csvToXml.py
convert CSV type register maps to XML ones compatible with regmap
Signed-off-by:Ionut Muthi <Ionut.Muthi@analog.com>
=> regmap: register map csv to xml convertor

core/include/core/scopymainwindow.h, core/src/scopymainwindow.cpp, gui/include/gui/restartdialog.h, gui/include/gui/widgets/popupwidget.h, gui/src/BasicPlot.cpp, gui/src/restartdialog.cpp, gui/src/widgets/popupwidget.cpp
=> Disable OpenGL preference when drivers are missing or version is too old

plugins/regmap/src/deviceregistermap.cpp, plugins/regmap/src/deviceregistermap.hpp, plugins/regmap/src/recyclerview/registermaptable.cpp, plugins/regmap/src/recyclerview/registermaptable.hpp, plugins/regmap/src/register/registermodel.cpp, plugins/regmap/src/register/registermodel.hpp, plugins/regmap/src/register/registersimplewidget.cpp, plugins/regmap/src/register/registersimplewidget.hpp, plugins/regmap/src/register/registersimplewidgetfactory.cpp, plugins/regmap/src/register/registersimplewidgetfactory.hpp, plugins/regmap/src/registermaptemplate.cpp, plugins/regmap/src/registermaptemplate.hpp, plugins/regmap/src/registermaptool.cpp, plugins/regmap/src/registermaptool.hpp, plugins/regmap/src/regmapplugin.cpp, plugins/regmap/src/xmlfilemanager.cpp, plugins/regmap/src/xmlfilemanager.hpp
no longer need to send bitsPerRow throw the app
=> Dev regmap register display update

gr-util/src/grtimechanneladdon.cpp, gui/include/gui/DisplayPlot.h, gui/include/gui/cursorcontroller.h, gui/include/gui/plotaxis.h, gui/include/gui/plotnavigator.hpp, gui/include/gui/plottracker.hpp, gui/include/gui/plotwidget.h, gui/include/gui/widgets/plotcursorreadouts.h, gui/src/DisplayPlot.cc, gui/src/cursor.cpp, gui/src/cursorcontroller.cpp, gui/src/plotaxis.cpp, gui/src/plotcursors.cpp, gui/src/plotnavigator.cpp, gui/src/plottracker.cpp, gui/src/plotwidget.cpp, gui/src/widgets/plotcursorreadouts.cpp
cursors and trackers are now updated based on PlotAxis units and formatter
=> Scopy 2.0: Generalized PlotAxis units and formatters

gr-util/src/grtimechanneladdon.cpp, gr-util/src/grtimeplotaddonsettings.cpp, gui/include/gui/plotautoscaler.h, gui/src/plotautoscaler.cpp
Added tolerance : value representing percentage extra to min and max value when plotting 
Moved xAxis var from constructor to function
=> gui: PlotAutoscaler update

pluginbase/src/preferenceshelper.cpp
Updated the format of PreferencesEdit to match the others
=> gui: fixed preferences edit ui

gr-util/include/gr-util/grtimeplotaddon.h, gr-util/src/grtimeplotaddon.cpp, gui/include/gui/widgets/plotbufferpreviewer.h, gui/include/gui/widgets/plotinfo.h, gui/src/widgets/plotbufferpreviewer.cpp, gui/src/widgets/plotinfo.cpp, plugins/datamonitor/include/datamonitorplugin/monitorplot.hpp, plugins/datamonitor/src/datamonitor/monitorplot.cpp
I made a standalone class (PlotBufferPreviewer) for the buffer previewer which contains the controller and the actual previewer.
=> gui/widgets/plotinfo: Removed buffer previewer from plotinfo.

CI/appveyor/install_macos_deps.sh, CI/appveyor/package_darwin.sh, azure-pipelines.yml
- workaround for homebrew
- updated search for python version
- added a fix for when macdeployqt fails
=> ci/macos: fix macos build

plugins/datalogger/include/dataloggerplugin/datalogger_api.hpp, plugins/datalogger/include/dataloggerplugin/dataloggerplugin.h, plugins/datalogger/include/dataloggerplugin/datamonitortool.h, plugins/datalogger/include/dataloggerplugin/menus/dataloggingmenu.hpp, plugins/datalogger/include/dataloggerplugin/menus/datamonitorsettings.hpp, plugins/datalogger/include/dataloggerplugin/menus/monitorselectionmenu.hpp, plugins/datalogger/src/datalogger_api.cpp, plugins/datalogger/src/dataloggerplugin.cpp, plugins/datalogger/src/menus/monitorselectionmenu.cpp
Implemented API calls for data logger plugin
=> Dev datalogger tool api

plugins/datalogger/.gitignore, plugins/datalogger/src/dataloggerplugin.cpp
Changed plugin priority and added git ignore file
=> datamonitor: added git ignore file

core/src/emuwidget.cpp, core/src/iiotabwidget.cpp, gui/src/stylehelper.cpp
These changes solve the labels displaying problem.
=> core/scopyhomeaddpage: Use grid layout in emuwidget and iiotabwidget.

iio-widgets/include/iio-widgets/iiowidgetfactory.h, iio-widgets/src/iiowidgetfactory.cpp
Add methods for automatically building an IIOWidget from an attribute from iio_channel, iio_device, iio_context
=> IIOWidgetFactory: Add buildAttrFor(...) methods

iio-widgets/include/iio-widgets/datastrategy/multidatastrategy.h, iio-widgets/src/datastrategy/multidatastrategy.cpp, iio-widgets/src/iiowidget.cpp, plugins/test/src/testtool.cpp
The MultiDataStrategy is a Data Strategy that can be added to an IIOWidget. In this strategy, the user can add multiple DSs that will be aggregated in the MultiDataStrategy.
=> Implement MultiDataStrategy for IIOWidget

plugins/pqm/include/pqm/acquisitionmanager.h, plugins/pqm/include/pqm/harmonicsinstrument.h, plugins/pqm/include/pqm/plottingstrategy.h, plugins/pqm/include/pqm/plottingstrategybuilder.h, plugins/pqm/include/pqm/rollingstrategy.h, plugins/pqm/include/pqm/settingsinstrument.h, plugins/pqm/include/pqm/swtriggerstrategy.h, plugins/pqm/include/pqm/waveforminstrument.h, plugins/pqm/res/pqm1.xml, plugins/pqm/res/pqmDataWriter.py, plugins/pqm/res/sineGenerator.py, plugins/pqm/src/acquisitionmanager.cpp, plugins/pqm/src/harmonicsinstrument.cpp, plugins/pqm/src/pqmplugin.cpp, plugins/pqm/src/rollingstrategy.cpp, plugins/pqm/src/settingsinstrument.cpp, plugins/pqm/src/swtriggerstrategy.cpp, plugins/pqm/src/waveforminstrument.cpp
Waveform:
- added rolling mode 
- added triggered mode 
- adapts to the old fw version
- changed plot sample rate to 5120 instead of 3200
Harmonics:
- removed 0th harmonic from plot and table 
Settings:
- logging support
=> PQM Changes

plugins/regmap/src/readwrite/fileregisterreadstrategy.cpp, plugins/regmap/src/readwrite/fileregisterreadstrategy.hpp, plugins/regmap/src/registermapsettingsmenu.cpp
when writing from file we need a way to read all values from the file
=> regmap: added read all for file read

gui/src/widgets/menuspinbox.cpp
=>  gui: fix menuspinbox spacing in horizontal layout

.github/workflows/linuxflatpakbuild.yml, .github/workflows/mingwbuild.yml, .github/workflows/ubuntu20build.yml, .github/workflows/ubuntu22build.yml
- actions/checkout@v3 --> v4
- actions/upload-artifact@v3 --> v4
- mikepenz/action-junit-report@v3.7.8 --> v4
=> Update Github Actions

gui/src/widgets/hoverwidget.cpp, plugins/m2k/src/old/network_analyzer.cpp
The commits reviewed and cherry-picked span from tag v1.4.1 up to the latest commit in the main branch (CI commits were omitted).
=> Apply fix commits from main to dev

plugins/m2k/src/old/oscilloscope.cpp, plugins/m2k/src/old/signal_generator.cpp
=> m2k: bugfixes - oversampling ratio and siggen run btn

gui/style/qss/generic/m2k.qss, plugins/swiot/src/faults/faultsdevice.cpp
=> Style pico fix

docs/user_guide/index.rst, docs/user_guide/troubleshooting.rst, gui/src/plotautoscaler.cpp
=> docs: update on ini file compatiblity

azure-pipelines.yml, ci/macOS/package_darwin.sh
- true -> True
- add workflow failure if one cp command exits with a non-zero status
=> ci/macos: fix a typo

plugins/pqm/include/pqm/swtriggerstrategy.h, plugins/pqm/src/swtriggerstrategy.cpp, plugins/pqm/src/waveforminstrument.cpp
- Auto triggering if there is no zero crossing.
=> pqm: Fix waveform sw trigger bug.

testing_results/testing_results_v2.0.0-beta-rc2/plugins/pqm/pqm_tests.rst, testing_results/testing_results_v2.0.0-beta-rc2/plugins/swiot1l/swiot1l_tests.rst
Tested:
- PQM Windows 10
- PQM Linux-arm64
- SWIOT1L Windows 10
- SWIOT1L Linux-arm64
=> afpop/testing v2.0.0 beta rc2

.github/workflows/appimage-arm64.yml, .github/workflows/appimage-armhf.yml, .github/workflows/appimage-x86_64.yml, .github/workflows/linuxflatpakbuild.yml, .github/workflows/mingwbuild.yml, azure-pipelines.yml
This commit disables shallow fetch inside the CI workflows.
=> Fix the commit history from About Page

core/include/core/scopymainwindow.h, core/src/scopymainwindow.cpp
=> core: added session specific save/load 

.github/workflows/generate_doc.yml, docs/test_report_generator.py
The 'generate_doc.yml' will behave as usual, with the exeption that once a PR to main closes and it comes from a branch that starts with 'testing_', it will extract from the branch name the version, create the test reports and and copy them to a folder for versioning called 'scopy_testing_results/<tested_version>'
=> workflows/docs: Add step for test report generation

plugins/dac/src/dacdatamodel.cpp, plugins/dac/src/dacdatamodel.h
=> dac: ensure filesize is also updated when data is modified while running

plugins/swiot/res/tutorial_chapters.json
=> swiot: fix tutorial step position.

plugins/dac/src/csvfilestrategy.cpp, plugins/dac/src/csvfilestrategy.h, plugins/dac/src/dacdatamodel.cpp
=> dac: make sure conversion does not generate data loss.

plugins/m2k/src/old/logicanalyzer/logicgroupitem.cpp, plugins/m2k/src/old/logicanalyzer/logicgroupitem.h, plugins/m2k/src/old/patterngenerator/pattern_generator.cpp
Fixed bug described here https://github.com/analogdevicesinc/scopy/issues/1949
=> Bug fix pattern generator

plugins/regmap/src/recyclerview/recyclerview.cpp, plugins/regmap/src/recyclerview/recyclerview.hpp, plugins/regmap/src/recyclerview/registermaptable.cpp
Increased the default rows available by default in regmap
=> regmap: fix scroll bug

iio-widgets/include/iio-widgets/iiowidgetbuilder.h, iio-widgets/src/iiowidgetbuilder.cpp, plugins/debugger/include/debugger/detailsview.h, plugins/debugger/src/iioexplorer/detailsview.cpp, plugins/debugger/src/iioexplorer/iioexplorerinstrument.cpp, plugins/debugger/src/iioexplorer/iiomodel.cpp
- The tree view will correctly show all attributes, including the ones that end with " _available"
- Add loading animation for the "Read All button"
=> iioexplorer: Misc fixes

docs/test_report_generator.py
The regex was missing a case where after **Steps**: there would be an empty space before the newline. This caused some UIDs to not correspond to their specific "Steps" sequence.
=> docs/test_report_generator: Fix regex

iio-widgets/include/iio-widgets/iiowidgetbuilder.h, iio-widgets/include/iio-widgets/iiowidgetutils.h, iio-widgets/src/guistrategy/checkboxguistrategy.cpp, iio-widgets/src/iiowidgetbuilder.cpp, iio-widgets/src/iiowidgetutils.cpp
Apply changes so that user can now set empty title as an option 
Made changes to checboxui not in compact mode will only apply text wrap 
Added IIOWidgetsUtil class where we can add commonly used functions related to IIOWidgets
Added functions for data conversion for custom combobox
=> Iiowidgets UI updates

plugins/datalogger/include/datalogger/datamonitor/datamonitormodel.hpp, plugins/datalogger/include/datalogger/datamonitor/dmmdatamonitormodel.hpp, plugins/datalogger/include/datalogger/datamonitor/readabledatamonitormodel.hpp, plugins/datalogger/include/datalogger/datamonitor/readstrategy/dmmreadstrategy.hpp, plugins/datalogger/include/datalogger/menus/channelattributesmenu.hpp, plugins/datalogger/src/datamonitor/datamonitormodel.cpp, plugins/datalogger/src/datamonitor/dmmdatamonitormodel.cpp, plugins/datalogger/src/datamonitor/readabledatamonitormodel.cpp, plugins/datalogger/src/datamonitor/readstrategy/dmmreadstrategy.cpp, plugins/datalogger/src/dmm.cpp, plugins/datalogger/src/menus/channelattributesmenu.cpp
added options to override scale and offset for data logger channels
=> datalogger: added options to override scale and offset for channels

.gitignore, docs/plugins/ad936x/ad936x.rst, docs/plugins/ad936x/ad936x_advanced.rst, docs/plugins/ad936x/index.rst, docs/plugins/index.rst
=> doc: ad936x doc

core/include/core/scopyaboutpage.h, core/src/scopyaboutpage.cpp, core/src/scopymainwindow.cpp, core/src/whatsnewoverlay.cpp
Make what's new to show if a new version of Scopy is installed using git hash
Add a button to open the What's new overlay to the About section
=> Whats new changes

docs/plugins/scripting/scripting.rst
Added a list with the script functions options
=> doc: add list of script functions

gr-util/src/time_sink_f_impl.cc, packages/generic-plugins/plugins/dac/src/txchannel.cpp
- fixed reversed adc buffers
- fixed dac dds not turning off in buffer mode
=> ADC and DAC fixes
